### ISSUE TITLE
Preview11: RouteId change in the routes config model is not breaking

### ISSUE THREAD

**Issue by dannyBies** [microsoft/reverse-proxy#1029]
### Describe the bug
I updated my application to the latest version ```1.0.0-preview.11.21223.5```. I tried running it without making any changes to the routes config model and I was surprised to see that everything was working. It turns out that the ```RouteId``` defined in my configuration is not used but the index of the array will now be my ```RouteId```  

### To Reproduce
Use the old config:
```
{
  "RouteId": "route1",
  "ClusterId": "cluster1",
  "CorsPolicy": "default",
  "Match": {
    "Path": "/route1/{**catch-all}"
  },
  "Transforms": [
    { "PathRemovePrefix": "/route1" }
  ]
},
```
This will result in something similar to:
![image](https://user-images.githubusercontent.com/3967506/119790439-d8362e00-becb-11eb-8768-b5c6da8f9aae.png)

### Further technical details
I would've expected a warning or error telling me that I am missing the correct ```RouteId``` as this could cause subtle bugs if your application is dependant on the ```RouteId```

- Include the version of the packages you are using ```1.0.0-preview.11.21223.5```
- The platform (Windows)

**Comment by MihaZupan** [comment]
Thanks for reporting this, definitely wasn't intended.

This issue applies to clusters & destinations as well.

@Tratcher can correct me here, but from what I understand, configuration is effectively flattened to a list like
```json
{
    "Clusters:myCluster1:Destinations:destinationA:Address": "foo",
    "Clusters:myCluster2:Destinations:destinationB:Address": "bar",

    "Clusters:0:Destinations:destinationA:Address": "foo",
    "Clusters:1:Destinations:destinationB:Address": "bar",
}
```
So the `IConfiguration` abstraction can't distinguish between an array and a dictionary with keys like `"0", "1", ...`.

Short of not accepting IDs that are also integers (or specifically banning "0" as being used), I'm not sure we can detect this.

**Comment by Tratcher** [comment]
I hadn't anticipated it would fail quite like that. @MihaZupan's assessment looks accurate.  Luckily the route id isn't used for much so it should work as is for most people.

We don't usually add mitigations for breaking changes between previews, only release notes. Since the failure is not obvious in this case we may want to add a temporary check that the obsolete "RouteId" label is no longer present on a route config object.

Here we could throw if `section["RouteId"]` returns a non-empty value:
https://github.com/microsoft/reverse-proxy/blob/bc0399b08a6f511ed638c690a2636ca7e3b4c023/src/ReverseProxy/Configuration/ConfigurationConfigProvider.cs#L138-L142

**Comment by Tratcher** [comment]
Clearing the milestone for triage review.

**Comment by samsp-msft** [comment]
Triage: Take the fix suggested by Tratcher in https://github.com/microsoft/reverse-proxy/issues/1029#issuecomment-849843294
