### ISSUE TITLE
Add metadata in DestinationConfig from service discovery

### ISSUE THREAD

**Issue by keira369** [microsoft/reverse-proxy#1104]
### What should we add or change to make your life better?
We found that the metadata feature [here](reverse-proxy/Discoverer.cs at d31b3886d3c5150ed46b2c1ffb4813e6c77b0588 · microsoft/reverse-proxy · GitHub) hasn't been enabled. With Service Fabric integration, we were hoping to pass more destination info through metadata from service discovery (e.g. ServiceUri, PartitionId, NamedPartitionName, ReplicaOrInstanceId, StatefulReplicaMode).

### Why is this important to you?
Having these information in metadata would help us reduce the look up latency for named partition stateful services to pick up the right destination and route the call to -  we can avoid looking up endpoints by querying service fabric once again since the information should already be provided in metadata.

**Comment by keira369** [comment]
Recopying the [link](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Freverse-proxy%2Fblob%2Fd31b3886d3c5150ed46b2c1ffb4813e6c77b0588%2Fsrc%2FReverseProxy.ServiceFabric%2FServiceDiscovery%2FDiscoverer.cs%23L225&data=04%7C01%7Ckejyang%40microsoft.com%7C76c8e4d80f7740f6d99d08d932a34bda%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637596499205987366%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AideCZxUU2%2BuAohnhP7GtyltBIQy9sI%2BDSB5hyHAFpg%3D&reserved=0) related to metadata feature.

**Comment by davidni** [comment]
@Tratcher @alnikola fyi. Kejia and I chatted about this one last week, looks reasonable. SF integration should stamp known metadata to elements (e.g. Clusters, Destinations) where this makes sense so that any necessary info is available from the YARP pipeline.

This should be a small change.

Design note: it would be good to approach this holistically so that we come up with reasonable nomenclature. In Island Gateway for example, we add a few of the following metadata keys already:

Applies to| Metadata Key | Meaning | Example value
-|-|-|-
Cluster|`__SF.ApplicationName` | Service Fabric app name of the SF service from which the YARP cluster was created|`fabric:/MyApp`
Cluster|`__SF.ServiceName` | Service Fabric service name from which the YARP cluster was created|`fabric:/MyApp/MySvc`
Cluster|`__SF.ApplicationTypeName` | Service Fabric Application Type of the SF service from which the YARP cluster was created|`MySvcType`
Cluster|`__SF.ServiceTypeName` | Service Fabric Service Type of the SF service from which the YARP cluster was created|`MySvcType`
Destination|`__SF.PartitionId`|Partition id of the SF replica|`<guid>`
...

**Comment by keira369** [comment]
> @Tratcher @alnikola fyi. Kejia and I chatted about this one last week, looks reasonable. SF integration should stamp known metadata to elements (e.g. Clusters, Destinations) where this makes sense so that any necessary info is available from the YARP pipeline.
> 
> This should be a small change.
> 
> Design note: it would be good to approach this holistically so that we come up with reasonable nomenclature. In Island Gateway for example, we add a few of the following metadata keys already:
> 
> Applies to	Metadata Key	Meaning	Example value
> Cluster	`__SF.ApplicationName`	Service Fabric app name of the SF service from which the YARP cluster was created	`fabric:/MyApp`
> Cluster	`__SF.ServiceName`	Service Fabric service name from which the YARP cluster was created	`fabric:/MyApp/MySvc`
> Cluster	`__SF.ApplicationTypeName`	Service Fabric Application Type of the SF service from which the YARP cluster was created	`MyAppType`
> Cluster	`__SF.ServiceTypeName`	Service Fabric Service Type of the SF service from which the YARP cluster was created	`MySvcType`
> Destination	`__SF.PartitionId`	Partition id of the SF replica	`<guid>`
> ...

Thanks David for adding this. For our scenario, it would be great if we could have the following metadata:
<html>
<body>


Applies to | Metadata Key | Meaning | Example value
-- | -- | -- | --
Cluster | __SF.ServiceName | Service Fabric service name from which the YARP cluster was created | fabric:/MyApp/MySvc
Cluster | __SF.StatefulReplicaMode | Replica selection mode for stateful services | Primary/ActiveSecondary etc.
Destination | __SF.PartitionId | Partition id of the SF replica | 123123
Destination | __SF.NamedPartitionName | The named partition name of the SF partition | 0
Destination | __SF.ReplicaId or __SF.InstanceId | ReplicaId for stateful services and InstanceId for stateless services | 123123
<html>

</body>
</html>
