### ISSUE TITLE
Add Cluster parameter to IProxyConfigFilter.ConfigureRouteAsync

### ISSUE THREAD

**Issue by Kahbazi** [microsoft/reverse-proxy#1229]
### What should we add or change to make your life better?
Add `ClusterConfig?` parameter to `IProxyConfigFilter.ConfigureRouteAsync`.
```diff
namespace Yarp.ReverseProxy.Configuration
{
    public interface IProxyConfigFilter
    {
-        ValueTask<RouteConfig> ConfigureRouteAsync(RouteConfig route, CancellationToken cancel);     
+        ValueTask<RouteConfig> ConfigureRouteAsync(RouteConfig route, ClusterConfig? cluster, CancellationToken cancel);
    }
}
```

### Why is this important to you?
Beside grouping for route config (#164), this could be used to apply certain rule for routes based on `cluster.Metadata`.

**Comment by Tratcher** [comment]
This is logistically challenging since the filter is called before a route has been associated with a cluster. We don't even have a dictionary of clusters yet, just a flat list.
https://github.com/microsoft/reverse-proxy/blob/16ab855a5be980a0cf5fd21e9a7028190b6e7dda/src/ReverseProxy/Management/ProxyConfigManager.cs#L212-L213
We could reverse these so clusters are verified first, but you'd still need a temporary dictionary of clusters to enable lookup for the associated routes.
