### ISSUE TITLE
Document Kestrel response header encoding

### ISSUE THREAD

**Issue by MihaZupan** [microsoft/reverse-proxy#1346]
From #1055:

Document Kestrel response header encoding (dotnet/aspnetcore#33776) [here](https://github.com/microsoft/reverse-proxy/blob/16ab855a5be980a0cf5fd21e9a7028190b6e7dda/docs/docfx/articles/http-client-config.md#httpclient).

**Comment by ChintanRaval** [comment]
hi Chris @Tratcher / @MihaZupan / @karelz .. i'm trying to use yarp and facing [this encoding issue](https://github.com/microsoft/reverse-proxy/issues/440) due to a downstream system returning non-ASCII chars in the response header. since I don't have control over the downstream system, I am trying to see how we can be more tolerant at yarp's end. 

now that aspnetcore/kerner [is updated](https://github.com/dotnet/aspnetcore/pull/33776) (thanks Chris!) to optionally be more tolerant to non-ASCII characters, how can we tell yarp to leverage the tolerance. is there something similar to RequestHeaderEncoding coming up like ResponseHeaderEncoding or so? 

I was hoping this documentation update issue might help make that clear. even if someone can give a TL;DR on how to achieve this without this documentation-update-issue being resolved, it'd be great.

**Comment by Tratcher** [comment]
You don't need to do anything YARP specific, you configure the Kestrel options directly in your proxy app.

**Comment by ChintanRaval** [comment]
ah sorry. thanks @Tratcher. i'll try something via appSettings.. or even code like the below. 

```c#
builder.WebHost.ConfigureKestrel(serverOptions =>
{
    serverOptions.ResponseHeaderEncodingSelector = _ => System.Text.Encoding.Unicode;
});
```
