### ISSUE TITLE
Better handle config validation and filter errors

### ISSUE THREAD

**Issue by halter73** [microsoft/reverse-proxy#140]
### What should we add or change to make your life better?

See https://github.com/microsoft/reverse-proxy/pull/47#discussion_r419791604 for context.

DynamicConfigBuilder currently reports config validation and IProxyConfigFilter errors to the ProxyConfigLoader (which just logs the error) and continues loading the next backend or route. This is true whether or not the errors occur during proxy startup or config reload.

I think proxy startup should fail if there is an error validating or processing configuration for any backend or route. On config reload, the proxy should continue using the last known good configuration.

In any case, the proxy should log config error at the "Critical" instead of the "Warning" log level.\

### Why is this important to you?

Easier debugging. A developer is a lot more likely to notice the proxy crashing at startup than an error log. Partially (re)loaded config putting the proxy in an inconsistent state could also be frustrating.

While discussing this offline, the scenario came up where an IProxyConfigFilter experiences a transient error loading config from a database. Even though this isn't a straight misconfiguration, I think loading a subset of the backends or routes is worse than just failing startup or using the last known good configuration.

**Comment by Tratcher** [comment]
@davidni thoughts? There current behaviors of dropping broken routes seemed deliberate in island gateway.

**Comment by davidni** [comment]
Both options (fail early Vs. keep going skipping bad backend configs) may make sense in different scenarios,

In our use case, routes are defined by various client teams running behind our proxy, and we discover those routes dynamically, similar to [Traefik's Service Fabric integration](https://docs.traefik.io/v1.7/configuration/backends/servicefabric/). If one of our client teams makes a mistake in their route configuration, **we surely don't want the entire gateway to stop**, nor do we want to cease taking route updates from other backends that remain well behaved.

Therefore we choose to keep going with the valid backends, and additionally (out of scope of this discussion) we also emit an "unhealthy" health report against any offending backends so they can fix detect and it (and so that Service Fabric might trigger a rollback in case they were in the process of rolling out bad bits).

I expect that any YARP configuration that relies on _dynamic service discovery_ would benefit from partial config updates.

A clean solution might be to off-load the preparation of a consistent new config to the dynamic discovery component. But to do that effectively, that component needs to be able to use YARP's internal validation routines.

**Comment by karelz** [comment]
Triage: We may want to introduce some scopes. We may want give more power / config to the users of YARP.

**Comment by Tratcher** [comment]
Speaking of scopes... https://github.com/microsoft/reverse-proxy/issues/164

**Comment by Tratcher** [comment]
This has changed a fair about with the new IProxyConfigProvider model.
https://microsoft.github.io/reverse-proxy/articles/configproviders.html#lifecycle

> I think proxy startup should fail if there is an error validating or processing configuration for any backend or route. On config reload, the proxy should continue using the last known good configuration.

That's now the behavior. Closing this as addressed.
