### ISSUE TITLE
Getting 404 on page resources when using PathRemovePrefix

### ISSUE THREAD

**Issue by tomaustin700** [microsoft/reverse-proxy#1460]
### Describe the bug
Hi,
I'm trying to do path based routing between two websites like this
https://domain.com/website1
https://domain.com/website2

I have a transform with PathRemovePrefix turned on and when navigating to the sites the pages resources (images, css, etc) are not loading as theirs paths are broken as their urls are incorrect.

### To Reproduce

This appsettings.json will duplicate the problem
```
{
  "Urls": "http://localhost:5000;https://localhost:5001",
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  "ReverseProxy": {
    "Routes": {
      
      "pengroute": {
        "ClusterId": "website2",
        "Match": {
          "Path": "/website2/{*any}"
        },
        "Transforms": [
          {
            "PathRemovePrefix": "/website2"
          }
        ]
      }
    },
    "Clusters": {
     
      "website2": {
        "Destinations": {
          "website2.com": {
            "Address": "https://www.partypeng.win"
          }
        }
      }
    }
  }
}
```

I'd expect if I went to https://localhost:5001/website2 the image from www.partypeng.win would load however it does not.

This seems to be a similar issue to #1156 and I'm guessing some rewriting is needed perhaps via middleware.

Would someone be able to point me in the direction of how to do this or if it's even possible at all. Thanks
### Further technical details

- Version 1.0.0.0
- Windows - dotnet 6

**Comment by tomaustin700** [comment]
Just to add to this, if I add a / to the end of the url (i.e. https://localhost:5001/website2/) it does actually work.

**Comment by Tratcher** [comment]
This pattern rarely works without the cooperation of the destination site. The problem is that the first request is OK, but then it generates links to dependent resources that don't include the "/website2/" prefix so the next requests fail to route.

The best option is to forward the prefix in a header like `"x-fowarded-prefix": "/website2/"` and have the destination app use that value when generating links.

The alternative requires parsing responses and re-writing links. YARP is not designed for that.

**Comment by tomaustin700** [comment]
Thanks @Tratcher.
