### ISSUE TITLE
AmbiguousMatchException in .NET 7, if YARP is used with other endpoints

### ISSUE THREAD

**Issue by glatzert** [microsoft/reverse-proxy#1864]
### Describe the bug
We use YARP as BFF (Backend-For-Frontend) Proxy in some of our web sites.
With .NET 7 RC1, we tried to move some pages to that and had consistentyl accross all apps Problems with an `AmbiguousMatchException`, which always would show the same route (e.g. /Index /Index /Index).

The problem could be removed be moving the call to `endpoints.UseReverseProxy()` below all other `endpoints.Use*` calls.
I debugged it and it seemed, that the addition of YARP will lead to a duplicate enumeration of all EndpointDataSources that where registered after YARP.

The problem does not occur with .NET 6.
I linked a repo with a small reproduction (basically empty razor pages + little YARP config).
The bug can be circumvented, when `app.UseReverseProxy()` is swapped with `app.UseRazorPages()`

### To Reproduce

https://github.com/glatzert/YARPBug (Net6 Project and Net7 Project are identical, besides the TFM)

### Further technical details

- YARP 1.1.1, Net 7.0 RC 1
- Windows

**Comment by Tratcher** [comment]
Since the main difference here is .NET 7, we'll discuss the routing details over in https://github.com/dotnet/aspnetcore/issues/44085.

As for auth, your repro doesn't include any auth, did you add that later or is it in the destination app? When you say 'the same symptoms as above', that's odd because auth doesn't use routing for the sigin-oidc endpoint, you shouldn't ever get a route conflict there. Is it really the same AmbiguousMatchException?

**Comment by glatzert** [comment]
There are more things at play, i think - the auth problem was a fragment of using a razor Page called Index.cshtml (with e,pty `@page` directive) and `MapFallbackToPage(/Index)` for an SPA, which also is a problem. I commented an existing issue about that...

**Comment by karelz** [comment]
Triage: Seems to be addressed in https://github.com/dotnet/aspnetcore/issues/44085
