### ISSUE TITLE
Reading SSL/TLS(?) content in ResposeTransform

### ISSUE THREAD

**Issue by artur-siwiak** [microsoft/reverse-proxy#1921]
### Describe the bug
When I'm trying to read response in ```ResponseTransform``` content seems to be encrypted (i guess that's the case). Is there a way to to read SSL/TLS response? Is it possible at all?

### To Reproduce
```
.AddTransforms(context =>
{
    context.AddResponseTransform(async response =>
    {
        var stream = await response.ProxyResponse!.Content.ReadAsStreamAsync();
        using var reader = new StreamReader(stream);
        // TODO: size limits, timeouts
        var body = await reader.ReadToEndAsync();
        Console.WriteLine(body);
    });
})
```

Got Exceptions? Include both the message and the stack trace
There are no exceptions.

### Further technical details
Yarp.ReverseProxy v.1.1.1
Platform: Windows 11

**Comment by Tratcher** [comment]
It won't be encrypted, HttpClient decrypts everything in order to read the response headers. However, it might be compressed, that looks as obtuse 😁.
https://microsoft.github.io/reverse-proxy/articles/transforms.html#response-body-transforms

Check the response Content-Encoding header for gzip, br, deflate, etc..

YARP disables decompression since it adds CPU overhead.
You can enable automatic decompression on SocketsHttpHandler like this:
https://microsoft.github.io/reverse-proxy/articles/http-client-config.html#configuring-the-http-client
https://learn.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.automaticdecompression?view=net-7.0#system-net-http-socketshttphandler-automaticdecompression

**Comment by artur-siwiak** [comment]
> It won't be encrypted, HttpClient decrypts everything in order to read the response headers. However, it might be compressed, that looks as obtuse 😁. https://microsoft.github.io/reverse-proxy/articles/transforms.html#response-body-transforms
> 
> Check the response Content-Encoding header for gzip, br, deflate, etc..
> 
> YARP disables decompression since it adds CPU overhead. You can enable automatic decompression on SocketsHttpHandler like this: https://microsoft.github.io/reverse-proxy/articles/http-client-config.html#configuring-the-http-client https://learn.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.automaticdecompression?view=net-7.0#system-net-http-socketshttphandler-automaticdecompression

Lol. I didn't consider compression. I'm ashamed of myself. Anyways yours solution works! Thanks for helping me
