### ISSUE TITLE
Large (split) cookie handling

### ISSUE THREAD

**Issue by tom-puckett** [microsoft/reverse-proxy#1929]
### Some details

**How many backends are in your application?**

- [ ] 1-2
- [x] 3-5 (and growing)
- [ ] 6-10
- [ ] 10+

**How do you host your application?**

- [ ] Kubernetes
- [ ] Azure App Service
- [x] Azure VMs
- [ ] Other Cloud Provider (please include details below)
- [ ] Other Hosting model (please include details below)

### What did you think of YARP?
YARP has been an important part of a new feature (described below) in our application.  In general I like it for the most part, especially that it fits into a well known architecture so I didn't have to learn a new tool from the ground up. There are some enhancements that I'd like to see happen, but this issue is mainly about one question that came up today. 

Our application is a portal that embeds content (traditionally static documents or dashboards) and we recently added support for a new type of content in the form of containerized application UIs, using YARP in the portal to forward appropriate requests.  The portal uses cookie based user authentication.  Today I realized that at least some portal users' identity cookies are being forwarded by YARP, which seems like a security issue because a containerized application (not under my control) could harvest authenticated user identities.  This came up after we learned about a user with a very large identity cookie.  The browser split the Identity cookie into multiple separate headers, causing an error in the back end application.  Perhaps YARP forwards that cookie only when it is split, I don't know. 

The question is whether this is somehow a solved problem and what to do about it.  I'd rather not just delete all cookies with a name starting with `AspNetCore.Identity.Application` (and the session and antiforgery cookies too) so I'd like to think there there is at least one of the following:

1. An existing named transform or configuration option that instructs YARP to remove any proxy related headers / cookies from the request to be forwarded (seems like a good default behavior)
2. A property in the `RequestTransformContext` that I can take advantage of to remove the appropriate headers / cookies that are not related to the back end application, but not remove headers / cookies with similar names that belong to the back end. 
3. If it is strictly related to splitting of the cookie, a fix to make the cookie removal work in that scenario too. 
4. Something else that's useful.

Separately, I'd be interested in these enhancements in YARP:
   - Ability to register for a callback (e.g. telemetry) every time a client sends a WebSocket message through YARP (could be async, no need to intervene).
   - Ability to configure websockets not to time out with the same idle timeout as http requests
     or
   - Ability to sustain websocket connections (both directions) by initiating ping messages from YARP

**Comment by Tratcher** [comment]
> An existing named transform or configuration option that instructs YARP to remove any proxy related headers / cookies from the request to be forwarded (seems like a good default behavior)

YARP already removes headers related to connection management by default. Cookies are forwarded by default since they are usually required by the back-end application. It's not related to cookie splitting. How would we identify a proxy related cookie? It's easy to remove the entire Cookie header with a transform (`"RequestHeaderRemove": "Cookie"`). However, there's nothing built in to filter out specific cookies. For that you'd need a custom transform that re-writes the header. https://microsoft.github.io/reverse-proxy/articles/transforms.html#addrequesttransform

> A property in the RequestTransformContext that I can take advantage of to remove the appropriate headers / cookies that are not related to the back end application, but not remove headers / cookies with similar names that belong to the back end.

Can you give an example? How should YARP distinguish between these?

> If it is strictly related to splitting of the cookie, a fix to make the cookie removal work in that scenario too.

Do you have an example of the split cookie headers? Cookies are not supposed to be split into multiple headers, only multiple values. There's an exception in HTTP/2, but the server is supposed to re-combine them. Kestrel didn't do that before .NET 7, but YARP worked aroud that.
https://github.com/microsoft/reverse-proxy/blob/c39fcf8c1fc574dc94c61d4bbb4222f1cd35c656/src/ReverseProxy/Forwarder/RequestUtilities.cs#L281-L291



> * Ability to register for a callback (e.g. telemetry) every time a client sends a WebSocket message through YARP (could be async, no need to intervene).

Take a look at 
https://github.com/microsoft/reverse-proxy/blob/c39fcf8c1fc574dc94c61d4bbb4222f1cd35c656/src/ReverseProxy/WebSocketsTelemetry/WebSocketsTelemetryExtensions.cs#L20

Right now it's just counting, but adding a callback should be possible. Try it, and if it works please file a separate issue for that feature.

> Ability to configure websockets not to time out with the same idle timeout as http requests
> or
> Ability to sustain websocket connections (both directions) by initiating ping messages from YARP

Everything needs to time out eventually. Since we use an activity based timeout it should be ok so long as any data or pings are flowing in either direction. We're not currently able to insert pings because we don't inspect the websocket traffic to know where the frame boundaries are, doing so would add significant perf overhead. The only component that does this is for telemetry, and it isn't set up to modify or insert anything. Pings really should be end-to-end, from the client or server, to ensure the whole connection is still active.

**Comment by tom-puckett** [comment]
Thanks, I'll likely submit a new issue requesting the new callback in the websocket telemetry consumer. 

> Everything needs to time out eventually.

After a websocket is upgraded it's a persistent connection, so it seems that an http oriented timeout would be less applicable and the connection lifetime would be managed differently than an http request.  I don't know whether the YARP architecture allows that, but it would be nice to somehow not have to work around the timeout issue in the proxied application, especially since it's not an issue without the proxy in the middle.

**Comment by tom-puckett** [comment]
> What would you want to do in such a callback?

In my current scenario I'm tracking timestamps of latest user activity in each proxied application so that I can delete a back end containerized application that becomes inactive for some time.  Our biggest user is hosting R-Shiny applications that load a page and then all subsequent traffic is on a websocket.  So I currently have no way to know how long a user is active.

**Comment by tom-puckett** [comment]
The connection uses ping/pong to keep the websocket alive, so I would need enough context in the callback to assess that.  Also some information about whether the message is client to server or reverse.  The actual message content is not my use case but I don't know where you might want to draw the line.

**Comment by karelz** [comment]
Triage: @tom-puckett are your questions answered here? If yes, can we close the issue? Thanks!

**Comment by tom-puckett** [comment]
I think the discussion has migrated to #1931.  As long as people can navigate here from the link in that issue it should be fine to close this one.
