### ISSUE TITLE
Use appropriate log level for errors

### ISSUE THREAD

**Issue by kheardCB** [microsoft/reverse-proxy#2025]
In the HttpForwarder, the log level for errors is Information. Can this be changed to Error? This may be an issue in other log messages in other files, but this is the main one I noticed.

[https://github.com/microsoft/reverse-proxy/blob/5210218470a00ea5359dfefb71d193aacd60b646/src/ReverseProxy/Forwarder/HttpForwarder.cs#L757](https://github.com/microsoft/reverse-proxy/blob/5210218470a00ea5359dfefb71d193aacd60b646/src/ReverseProxy/Forwarder/HttpForwarder.cs#L757)

Background:
I am using Serilog for logging and setting the MinimumLevel override for "Microsoft.AspNetCore" and "Yarp.ReverseProxy.Forwarder" to Warning. This accompanied with the "UseSerilogRequestLogging" option allows the service to omit one log line per request. In this setup, any errors are not being logged because they are set as Information, not Error.

I would gladly make the change myself and create a Pull Request, if that would be helpful.

**Comment by Tratcher** [comment]
The main concern here is that we don't want to log anything at the Error level that is caused by an external entity that you can't do anything about, that floods logs unnecessarily. Errors should be actionable within the current app. Timeouts, disconnects, etc. are all expected within normal proxy operations.

To look at the proxy results and decide which ones you want to react to check here:
https://github.com/microsoft/reverse-proxy/blob/029e731a95c08a77af37700b1ab6ecd99e694d83/docs/docfx/articles/middleware.md#error-handling

https://github.com/microsoft/reverse-proxy/blob/79a7b806688311fd2cca2ca67dc7cc418c7925ab/docs/docfx/articles/direct-forwarding.md#error-handling

**Comment by karelz** [comment]
Triage:
- `Error` level should be only for YARP problems that are actionable - see [list in code](https://github.com/microsoft/reverse-proxy/blob/03a4d6a91b9b65f90e8c616bebc77e1338bec81a/src/ReverseProxy/Forwarder/HttpForwarder.cs#L1063-L1081).
- `Warning` level should be for any unsuccessful proxying, things YARP is able to recover from - e.g. destination going out, client-side problems with network
    - Note: `Warn` level is turned on by default by templates
- `Information`/`Verbose` level should be for all successful log entries.

It is a one-line change in https://github.com/microsoft/reverse-proxy/blob/03a4d6a91b9b65f90e8c616bebc77e1338bec81a/src/ReverseProxy/Forwarder/HttpForwarder.cs#L992-L993
@kheardCB are you interested in submitting a PR for it?

**Comment by kheardCB** [comment]
@karelz Sure, I can submit a PR.
