### ISSUE TITLE
ArrayPool does not always work well when renting/returning happens on different threads.

### ISSUE THREAD

**Issue by saber-wang** [microsoft/reverse-proxy#2026]
According to the discussion in https://github.com/dotnet/runtime/issues/58974, ArrayPool does not always work well when lease/return occurs on different threads.

Is this implementation the same as discussed in https://github.com/dotnet/runtime/issues/58974?
https://github.com/microsoft/reverse-proxy/blob/8e9e3732b80daf4743e308124c14696e55cec18f/src/ReverseProxy/Forwarder/StreamCopier.cs#L44-L136

**Comment by MihaZupan** [comment]
That discussion is mostly talking about a scenario where you are already at the very edge of total available memory. In a scenario where you don't exactly control the amount of resources at any given moment (like YARP), you should operate with sufficient memory headroom to avoid such issues.

The default array pool currently uses ThreadLocal storage to speed up renting & returning. This means that there's a small per-thread cache of arrays that won't be used by other threads.
The arrays that YARP uses are relatively small (currently 64 KB), so this won't meaningfully impact the memory consumption of the process.

Aside from that, the pool can "steal" arrays from other cores to avoid wasting them. While being slightly more expensive than thread-local storage, it means you can efficiently share buffers even when they are rented and returned from different threads.
YARP also doesn't necessarily hop threads that often between renting and returning due to our use of zero-byte reads. Once we have a buffer, reads should generally complete synchronously. Writes also tend to complete synchronously unless you saturate kernel buffers.

The default array pool is currently the best option we have to pool arrays, and we haven't seen any evidence of it being problematic in the context of YARP. Are you seeing evidence to the contrary?

**Comment by saber-wang** [comment]
Thank you for your answer.
