### ISSUE TITLE
How do I update YARP settings at the same time when the YARP is hosting on App Service with multiple instances

### ISSUE THREAD

**Issue by takashiuesaka** [microsoft/reverse-proxy#2058]
Hi all,

I am trying to host YARP on Azure App Service that scales more than 2 instances because of the availability.
I need to change multiple YARP settings at the same time when those are running, but I don't want to restart App Services.

How do I do?

**Comment by samsp-msft** [comment]
YARP has file change detection for the configuration file. So if the file changes on disk, YARP will detect that change and update their configuration based on the new file.

The question then is for app-service can you update files across multiple instances without having to restart the instance. I know you can get a shell into the instance via kudu from the portal, but that would be for a specific instance. App service uses a local cache which is updated only when the app is restarted. https://learn.microsoft.com/en-us/azure/app-service/overview-local-cache

In this case the best approach would probably be to have a custom config provider that will pull the results from:
- A storage location that is mapped into all the apps
- A separate service (maybe a function) that will return the config as json that can then be hydrated to objects.

**Comment by takashiuesaka** [comment]
Thank you for you advice.
I'll try to implement custom provider.

**Comment by pinkfloydx33** [comment]
If you're able, you might want to look at Azure App Configuration, which has a .NET configuration provider and aspnet-plugin that can refresh on an interval and/or when specific configuration is changed. The updates across instances aren't performed *exactly* at the same time though since their startup time will impact the refresh timers. Using the aspnet Middleware however, it will attempt to refresh upon requests into the application. This has proven to be "good enough" for our use cases.

While they don't support _files_ they do support specifying single settings ie. `MySection:SomeValue`, as well as entire (or partial) _sections_ ie. `MySection` . The latter is achieved by supplying valid JSON as the configuration value and a content type of "application/json". It can also integrate with Azure Key Vault if necessary and has feature-flag support. 

All of these will properly layer on top of your base configuration as they are just another configuration source.

**Comment by samsp-msft** [comment]
@benjaminpetit - can you publish your Orleans configuration sample as a gist or something - as that would be another alternative.

**Comment by takashiuesaka** [comment]
@pinkfloydx33 - thank you very much for your kind advice. It looks like using "Azure App Configuration" is the best way to go!
Do you know if there is sample code available?

**Comment by pinkfloydx33** [comment]
Hey no prob! Lots of people (in my experience) aren't aware the service exists, so glad to help. We've been using it since it went GA and love it. There are samples in the Microsoft docs somewhere but I don't have anything available off hand (on my cell), sorry.

A couple things I forgot to mention... First is that it also includes an `IConfigurationRefresher` (I think that's the name) interface that let's you trigger a refresh yourself outside the intervals. This is the mechanism that the [Aspnet Middleware](https://www.nuget.org/packages/Microsoft.Azure.AppConfiguration.AspNetCore) uses to check/refresh as requests come into the app. If you use a message bus or some other means to communicate between instances of your app, you could leverage this interface in combination to actually achieve synchronized updates, if you need something better than the builtin behavior that is. 

Second is that the service doesn't offer any sort of replication to secondary instance/regions, which _could_ be a deal breaker. However, they do have an example in the docs of a reference implementation for an Azure Function that can be used to sync configuration to a secondary Azure App Config instance (we do this too). You can then add multiple instances of the provider to your app (using different endpoints, set to "optional") to enforce fallback to the secondary instance.

**Comment by takashiuesaka** [comment]
@pinkfloydx33 - Thanks so much for the additional information!
I have created a sample application for YARP using Azure App Configuration based on your information.
The initial screen works fine, but the auto-refresh does not work after updating the Azure App Configuration values. If you don't mind, could you please tell me where I can fix this?

```csharp
using Microsoft.Extensions.Configuration.AzureAppConfiguration;

namespace YarpSampleApp;

public class Program
{
    public static void Main(string[] args)
    {
        var builder = WebApplication.CreateBuilder(args);

        var connectionString = builder.Configuration["AzureAppConfiguration:ConnectionString"];

        builder.Configuration.AddAzureAppConfiguration(options =>
        {
            options.Connect(connectionString)
                .Select("ReverseProxy:*", LabelFilter.Null)
                .ConfigureRefresh(refresh =>
                {
                    refresh.Register("ReverseProxy:Sentinel", refreshAll: true)
                        .SetCacheExpiration(TimeSpan.FromSeconds(10));
                });
        });

        builder.Services.AddReverseProxy()
            .LoadFromConfig(builder.Configuration.GetSection("ReverseProxy"));

        var app = builder.Build();

        app.MapReverseProxy();

        app.Run();
    }
}
```

**Comment by pinkfloydx33** [comment]
You have to make a change to your `ReverseProxy:Sentinel` variable in azure app config. Once you do that it should be eligible to reload around the refresh interval. However I think(?) you may have to trigger the refresh via the configuration refresher interface. If instead you add the Aspnet Middleware I linked (before MapReverseProxy) it'll happen automatically so long as there's some traffic into the app.

**Comment by karelz** [comment]
Triage: Seems to be answered - thank you @pinkfloydx33 for your help here!
Closing.
