### ISSUE TITLE
High memory usage of YARP compared to Ocelot Gateway

### ISSUE THREAD

**Issue by themkarimi** [microsoft/reverse-proxy#2192]
### Describe the bug
We are in the process of moving from Ocelot to YARP but we have seen something strange. although CPU usage is identical between these two services but YARP is consuming a higher amount of memory. we have 5 instances of ocelot which all of them take 9GB of memory(cumulatively)  but for 5 instances of YARP  the memory usage is 17-18GB. we are hosting our services on our on-prem kubernetes cluster. 

### To Reproduce
host the latest version of YARP in kubernetes.

### Further technical details

YARP version: 2.0.1
Platform : Kubenetes 1.22

**Comment by Tratcher** [comment]
What version of .NET is this running on?

Have you done any memory profiling?

**Comment by nquandt** [comment]
NAME                               CPU(cores)   MEMORY(bytes)
yarp-controller-774489f998-4j29x   1m           95Mi
yarp-proxy-7777f8594c-mn9mw        441m         332Mi

I know it doesn't help much without more context, but I am able to run a single proxy instance to serve the majority of our web traffic (3 million per 24hrs), and have an average memory consumption of 300-500mb running on a Standard_D4s_v3 in azure aks.

I have roughly 40 routing rules in my table, and also have other middleware's in my deployment so i am not sure that vanilla YARP would take ~3.5GB per instance.

Though I do notice my NODE uses roughly 3.5Gb of memory due to things like logging, dns, etc also hooking in.

Are you running a "1 pod per node" strategy? I.e. an entire dedicated VM for each application

**Comment by themkarimi** [comment]
> What version of .NET is this running on?
> 
> Have you done any memory profiling?

we are using dotnet7 at the moment.
we haven't done any memory profiling yet, but we suspect memory leak could be a reason.

**Comment by themkarimi** [comment]
> NAME CPU(cores) MEMORY(bytes) yarp-controller-774489f998-4j29x 1m 95Mi yarp-proxy-7777f8594c-mn9mw 441m 332Mi
> 
> I know it doesn't help much without more context, but I am able to run a single proxy instance to serve the majority of our web traffic (3 million per 24hrs), and have an average memory consumption of 300-500mb running on a Standard_D4s_v3 in azure aks.
> 
> I have roughly 40 routing rules in my table, and also have other middleware's in my deployment so i am not sure that vanilla YARP would take ~3.5GB per instance.
> 
> Though I do notice my NODE uses roughly 3.5Gb of memory due to things like logging, dns, etc also hooking in.
> 
> Are you running a "1 pod per node" strategy? I.e. an entire dedicated VM for each application

we are distributing each pod in different nodes so 1 pod 1 node is the strategy here.

**Comment by themkarimi** [comment]
> Triage:
> 
> * @samsp-msft mentioned that ASP.NET uses server GC by default, which will consume all memory you give it - see [doc](https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/workstation-server-gc) ... you can do an experiment and swap it to workstation GC to see if it behaves differently
> * You might want to take a dump and see where the memory is being used
> * Or use memory profiler to see what is going on
> 
> Without additional data, it is not actionable for us.

so it was true, by applying memory limit to the yarp deployment its memory usage decreased significantly. thanks for you response.
