### ISSUE TITLE
Callbacks: Route applicability

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#230]
I was thinking in the shower that we are not using the fact that we can have user code readily accessible to us. In the case of routes, we have been talking about needing a language to describe the conditions for when the route should apply. We already have it - its called C# (,F# or other .NET code).

What if we defined the signature for a callback function then in the route config it could specify the full name of a static function that matches the signature. At config load time, we would resolve the name, so we could invoke with minimum overhead.
The function would be passed:
* the request header(s), 
* the configuration object for the route
  * is the config structure extensible - can I put my own data in there and have it hydrated?
and then return true/false if the route matches the rule.

App code would require that the assembly is loaded at startup. For a pre-built binary we could have a config way to specify an assemblies so it possible in that case too.

**Comment by samsp-msft** [comment]
@Tratcher

**Comment by Tratcher** [comment]
Note routing is not a linear search, there's a tree built up from the various constraints so it can efficiently find a match. That said, your point is still relevant for other kinds of extensibility.

If they have to write custom code in the app to define that static method, then they can also write the code to wire it up to a route from metadata. We'd only be able to do it via reflection. Since they have the dependencies they may be able to call the indicated method directly, and use simpler identifiers than a fully assembly qualified name.

The pre-built exe scenario is admittedly more constrained, but we've been intentional about not adding complicated features like this to that scenario.

**Comment by samsp-msft** [comment]
Not applicable
