### ISSUE TITLE
Need Help: Incorrect URL Transformation

### ISSUE THREAD

**Issue by Kiryuumaru** [microsoft/reverse-proxy#2439]
Hello,

I'm reaching out for assistance with a challenge I've encountered while using YARP. Firstly, I want to express my gratitude for providing such a valuable library.

### Issue Description:

I'm currently facing an issue with URL transformation when proxying a website. Here's the scenario: I'm attempting to proxy `https://github.com/microsoft` using the endpoint `http://localhost:5000/github/microsoft`. Initially, the proxying works as expected. However, upon clicking any links within the proxied page, the URL transforms incorrectly. Instead of maintaining the `/github` prefix, it redirects to `http:/localhost:5000/clickedLink`, when it should ideally lead to `http:/localhost:5000/github/clickedLink`.

### Configuration:
```
{
  "ReverseProxy": {
    "Routes": {
      "githubWebsite": {
        "ClusterId": "github",
        "Match": {
          "Path": "/github/{**Remainder}"
        },
        "Transforms": [
          {
            "PathRemovePrefix": "/github"
          }
        ]
      }
    },
    "Clusters": {
      "github": {
        "Destinations": {
          "destination1": {
            "Address": "https://github.com"
          }
        }
      }
    }
  }
}
```

I'd really appreciate some pointers on how to fix this. Thanks a bunch for your help!

**Comment by MihaZupan** [comment]
This may happen because the `href`s defined by the website are using absolute paths instead of relative ones (assuming there's no prefix), redirecting the browser to a url without your prefix.
Or the website could return a 3XX redirect response that sends the browser to a different path or a different host entirely.
Or the website could be using JavaScript that does redirects.

You can try to fight such things by rewriting the response html, rewriting the location headers, etc., but this is difficult to do reliably.

Ideally, you'll want the websites behind the proxy to play nice and not make assumptions that they'll never be behind a proxy (generally this means proxying sites you own).
The better approach is generally to make changes to the website itself by correcting how it generates links/redirects, relying on things like the `x-forwarded` headers.

**Comment by MihaZupan** [comment]
Closing as answered.
Feel free to reopen if there's something we missed.
