### ISSUE TITLE
Troubleshooting Debugging Issue After .NET Framework Upgrade: Breakpoints Not Triggering in CMS

### ISSUE THREAD

**Issue by rubenc57** [microsoft/reverse-proxy#2494]
🚀 Hey everyone, seeking some advice on upgrading my old webforms website named CMS, which currently runs on .NET Framework 4.8.

I've embarked on the journey to migrate it to a newer .NET version, opting for a side-by-side incremental project upgrade approach. As part of this transition, CMS is now linked to CMSCore via a Yarp proxy.

Everything seems to be functioning smoothly; I can execute CMSCore through a razor page, and navigating to an aspx page from CMS works flawlessly.

However, I've encountered an issue while attempting to debug code within CMS, in any .aspx.cs file. Despite setting breakpoints, they fail to trigger, displaying the message:

*"The breakpoint will not currently be hit. No symbols have been loaded for this document."*

Before upgrading to CMSCore, debugging within CMS was functioning well.

Any insights on how to resolve this would be greatly appreciated! Thanks in advance. 🙏

**Comment by MihaZupan** [comment]
I don't believe this issue is related to YARP. It might be worth asking in the https://github.com/dotnet/upgrade-assistant repo.

As a quick guess, if you're starting multiple projects in VS, make sure that their configuration is set to "Debug" and "Start".
![image](https://github.com/microsoft/reverse-proxy/assets/25307628/ccf81f7b-5658-4a72-8be2-8dfcfdc3374d)
