### ISSUE TITLE
Help Needed: Blank Screen Issue with Microsoft Reverse Proxy in .NET Core

### ISSUE THREAD

**Issue by rubenc57** [microsoft/reverse-proxy#2504]
Hi everyone,

I'm currently working on incrementally updating my WebForms website using the Microsoft Reverse Proxy in a new .NET Core application. I've added the necessary services in `program.cs`, but when I run the app, I encounter a blank screen. Here is the relevant code snippet from my `program.cs`:

```csharp
builder.Services.AddSystemWebAdapters()
    .AddJsonSessionSerializer(options =>
    {
        options.RegisterKey<string>("MachineName");
        options.RegisterKey<DateTime>("SessionStartTime");
        //options.RegisterKey<SessionDemoModel>("DemoItem");
    })
    .AddRemoteAppClient(options =>
    {
        options.RemoteAppUrl = new(builder.Configuration["ProxyTo"]);
        options.ApiKey = builder.Configuration["RemoteAppApiKey"];
    })
    .AddSessionClient();
```
If I remove the builder.Services.AddSystemWebAdapters() snippet, index page is shown again

I've double-checked my configuration settings and everything seems to be in place. However, when I execute the app, all I get is a blank screen without any error messages or logs that indicate what might be going wrong.

### Details:
- **Framework**: .NET Core
- **Proxy**: Microsoft Reverse Proxy
- **Configuration**: 
  - `ProxyTo` and `RemoteAppApiKey` are set in the configuration file.

### Troubleshooting Steps Taken:
1. Verified configuration settings in `appsettings.json`.
2. Checked for any runtime errors or logs – none found.
3. Uncommented the `RegisterKey<SessionDemoModel>("DemoItem")` line – no change.

### Has anyone experienced a similar issue or have any ideas on how to resolve this?

Any help or suggestions would be greatly appreciated!

I'm following this tutorial: https://youtu.be/_XG3EYRcgY8?si=2ARtMWNSIcIDEvCO

Thanks in advance.

**Comment by MihaZupan** [comment]
It may be better to open an issue in https://github.com/dotnet/systemweb-adapters since you're using that tooling unless there's an indication that YARP is misbehaving.

As a debugging step, if you're not seeing the resources you want on the website, I'd recommend looking at the developer tools in the browser in case there are any errors present in the console.
You should also look at the networking tab to see if the correct resources are being requested and whether those requests are failing.

If the right requests are being made, but are failing, you can look at the logs in the .NET Core app for details (you may have to increase the LogLevel verbosity in your `appsettings.json`).

**Comment by rubenc57** [comment]
Thank you

I'll do that
