### ISSUE TITLE
Consistency in Configuration :  Object Structures vs Arrays

### ISSUE THREAD

**Issue by johnazariah** [microsoft/reverse-proxy#279]
### Some details

We're trying to use YARP for our test environment and we're basically coming up with ways to rewrite the appsettings.json every time we register a new cluster.

Just a design question - Is there a reason why `Clusters` and `Destinations` are _objects_ and not _arrays_? It would appear that these are homogenous collections, and it makes sense to have them as arrays so they are easy to update...

**How many backends are in your application?**

- [ ] 1-2
- [ ] 3-5
- [X ] 6-10
- [ ] 10+

**How do you host your application?**

- [ ] Kubernetes
- [ ] Azure App Service
- [ X] Azure VMs
- [ ] Other Cloud Provider (please include details below)
- [ ] Other Hosting model (please include details below)

### What did you think of YARP?

**Comment by Tratcher** [comment]
> Just a design question - Is there a reason why `Clusters` and `Destinations` are _objects_ and not _arrays_? It would appear that these are homogenous collections, and it makes sense to have them as arrays so they are easy to update...

Each cluster is a unique object with an unique ID. The set of Clusters is also un-ordered so an array is not needed here. The same goes for destinations.

As for routes, those are an array because ordered can matter when matching patterns.

All that said, we are continuing to evaluate the overall config design are are likely to revisit each of these points.

**Comment by johnazariah** [comment]
Hi Chris

I think the `Cluster` object is entirely reasonable, but the `Clusters` collection I think should be an array for ease of serialization/deserialization. Ditto for the `Destinations` collection.

Right now we’re trying to parse the `ReverseProxy` node of the configuration JSON, and not having dynamic collections modelled as arrays makes it much harder to work with! 😊

-J

**Comment by johnazariah** [comment]
I think the `Cluster` object is entirely reasonable, but the `Clusters` collection I think should be an array for ease of serialization/deserialization. Ditto for the `Destinations` collection.

Right now we’re trying to parse the `ReverseProxy` node of the configuration JSON, and not having dynamic collections modelled as arrays makes it much harder to work with! 😊

**Comment by amweiss** [comment]
> I think the `Cluster` object is entirely reasonable, but the `Clusters` collection I think should be an array for ease of serialization/deserialization. Ditto for the `Destinations` collection.
> 
> Right now we’re trying to parse the `ReverseProxy` node of the configuration JSON, and not having dynamic collections modelled as arrays makes it much harder to work with! 😊

@johnazariah I'm interested in what you're approach is here, we were looking at injecting `IClustersRepo` and then using the `GetClustersAsync` and `SetClustersAsync` since it's handling the serialization for us and we can just deal with the objects.

**Comment by Tratcher** [comment]
@amweiss FYI we anticipate removing IClustersRepo soon. https://github.com/microsoft/reverse-proxy/issues/277

Get/SetClustersAsync doesn't currently do any serialization, it's an in-memory store.

**Comment by Tratcher** [comment]
You both seem more interested in a code based approach than a config based one, correct? You're only using the config file because we haven't given you a better alternative?

Let me outline the current code based model to unblock you. (We plan to refactor this for #277, but you can get started).
The [ProxyConfigLoader](https://github.com/microsoft/reverse-proxy/blob/a3b5e1b9b03fcec8bc764b033b5c066838a8ffe9/src/ReverseProxy/Configuration/ProxyConfigLoader.cs) is a good example, and I think it only uses public APIs that you should also be able to call.
- You provide a complete set of `Cluster`s to `IClustersRepo` and `ProxyRoute`s to `IRoutesRepo`. 
- Then you call `IReverseProxyConfigManager.ApplyConfiugrationAsync` to let the proxy know new data is available.
- If you need to apply a change later then update the repos as needed and call ApplyConfiugrationAsync again. Just don't do overlapping updates.
- You can also mimic ProxyConfigLoader's lifetime model where it implements IHostedService to be notified when the app starts and stops.

Let me know how that works for you.

**Comment by amweiss** [comment]
My use case is more for inspection rather than configuration, thus why the in-memory model was working for us. We used it to create a health check endpoint that would report out configuration and hit the upstream health checks. File based config works for us, and probably is consistent with a future state connected to Consul or the like.

**Comment by samsp-msft** [comment]
Dedupe to config cleanup work

**Comment by Tratcher** [comment]
> As for routes, those are an array because ordered can matter when matching patterns.

Disregard, registration order does not affect route resolution. The most specific match is used.

**Comment by sdekock** [comment]
Objects are a lot nicer when you are overriding/appending routes in an appsettings.Development.json files.
With the array syntax for the routes we now have to use the array index syntax "Routes:<index>" to append routes.

**Comment by Tratcher** [comment]
#893 also found that named route objects make it easier to override fields from environment variables.

**Comment by Tratcher** [comment]
Triage: Yes, lets use objects for routes to be consistent with clusters.
