### ISSUE TITLE
Outbound http connections to destinations are configurable 

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#282]
https://github.com/dotnet/runtime/issues/987

**Comment by samsp-msft** [comment]
Runtime feature: Enables control of the version to prevent connections from being downgraded.

**Comment by Tratcher** [comment]
A partner requires this for use with IHttpProxy because they prefer HTTP/1.1 for their scenarios. We currently default to HTTP/2.

Proposal:
RequestProxyOptions is used with IHttpProxy and could also be exposed as per-cluster configuration.
https://github.com/microsoft/reverse-proxy/blob/4bd161b6b357e2f146159dd8aef843b6e67fc4a7/src/ReverseProxy/Service/Proxy/RequestProxyOptions.cs#L9-L22

This would also address https://github.com/microsoft/reverse-proxy/issues/319 (configurable timeouts).

Make the http version and version policy (5.0 only) available on the options and then use them when constructing requests in HttpProxy.

Should the version property be nullable to allow you to preserve the incoming request version?

**Comment by Tratcher** [comment]
The version policy should also be added to the RequestParametersTransformContext so it can be customized by transforms.
https://github.com/microsoft/reverse-proxy/blob/6311df4abe1ce10c6274c5212600011886cac2c6/src/ReverseProxy/Service/RuntimeModel/Transforms/RequestParametersTransformContext.cs#L22
