### ISSUE TITLE
502 - Response when routing to Azure App Website - GET requests proxied with Transfer-Encoding

### ISSUE THREAD

**Issue by jeremielumandong** [microsoft/reverse-proxy#323]
### Describe the bug
Can you please show me the correct settings I need to add to allow Azure App Service application to be loaded in the Proxy. I'm trying to replace our existing Node Reverse Proxy to this one and I can't make it work. The node version is loading properly the website.

### Steps:

Added a simple Angular App as Front End as Azure App Service and configure that as the destination address.
Calling it from the YARP Proxy Server returns 502. I tried removing the ARR affinity in the Azure Website and still not working.

### Error:

{StatusCode: 502, ReasonPhrase: 'Bad Gateway', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Server: Microsoft-IIS/10.0
  Date: Mon, 13 Jul 2020 19:40:54 GMT
  Content-Type: text/html
  Content-Length: 1477
}}

**Comment by Tratcher** [comment]
Can you please share the config that you already tried?

**Comment by jeremielumandong** [comment]
My sample config below. 

"ReverseProxy": {
    "Clusters": {
      "sample_ui": {
        "Destinations": {
          "backend_ui": {
            "Address": "https://proxyui.azurewebsites.net/"
          }
        }
      }
    },
    "Routes": [
      {
        "RouteId": "route1",
        "ClusterId": "sample_ui",
        "Match": {
          "Methods": [
            "GET",
            "POST"
          ],
          "Hosts": [
            "localhost"
          ],
          "Path": "/ui/{**catchall}"
        },
        "Transforms": [
          {
            "PathRemovePrefix": "/ui"
          },
          {
            "X-Forwarded": ""
          }
        ]
      }
    ]
  }

**Comment by Tratcher** [comment]
Hmmm, this indicates an error in the application.
"502 - Web server received an invalid response while acting as a gateway or proxy server.
There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server."

However, it only happens when going through YARP. I was able to repro this against your site and one random other azurewebsites.net site. I'll dig a little deeper.

**Comment by Tratcher** [comment]
Notes:
- It still doesn't work if I use Fiddler as the client to send an empty request, so it's not related to any of the request fields provided by the browser.
- It does work if I run YARP in IIS Express rather than Kestrel. That might be because of how https://github.com/microsoft/reverse-proxy/issues/255 makes all requests not have a body in IIS.
- I have seen proxied HTTP/1.1 GET requests end up with a `Transfer-Encoding: chunked` header. Kestrel wouldn't care about that, but azurewebsites might. That happens because the HttpProxy code assumes all requests have a body:
https://github.com/microsoft/reverse-proxy/blob/24c0c5a969bb025dd7a355f0b62ee4cbac96c99f/src/ReverseProxy/Service/Proxy/HttpProxy.cs#L372-L404

Good news:
I was able to temporarily fix this by adding a check in the above SetupCopyBodyUpstream code to only generate a HttpContent object for POST requests.

Bad news:
There's no workaround from user code.

Next steps:
We're going to have to play with this more to find the right way proxy requests that don't have a body.

**Comment by jeremielumandong** [comment]
For now, I'm using your temporary fix to continue with my POC and the page is loading. We are planning to move our on-prem application to azure.
