### ISSUE TITLE
Add support for Azure Functions

### ISSUE THREAD

**Issue by murilocurti** [microsoft/reverse-proxy#350]
It will be very important to choose what host type the app can be deployed.

**Comment by galvesribeiro** [comment]
Hey @murilocurti !

Can you elaborate more on that? How do you think the reverse-proxy would be useful on Az Func or serverless workloads like that?

I'm curious to understand use cases for it in the serverless scenario.

**Comment by murilocurti** [comment]
I see Azure Functions like an Asp.Net Core hosting diversification when used with http triggers.
Serverless has some advantages because don't require all the scaling options as standard App Service Plans.

If the availability of reverse proxy is limited to regular Asp.Net Core apps, developers will be forced to work with App Service Plans or VMs.

It's more to let developers free to choose what is best for each scenario. I know that is perfectly possible to use the regular Asp.Net Core hosting options.

Here at Space Needle we rely more on Azure Functions than the other host options. And it definitely worse using.

Is it enough details about the request?

Best Regards

**Comment by galvesribeiro** [comment]
Hey, 

As we discussed offline, I understand your points and desires with it. It would be nice to have the reverse-proxy capabilities on Azure Functions even though I'm pretty sure this project would be able to run (with some adaptations) in Azure Function project, we have some drawbacks from the serverless approach that may ruin the whole benefits of it (or any reverse-proxy per se) brings to the table.

To name a few:
1. Cold-start time of functions will cause poor performance handling requests;
2. Every time a function start, it would start the reverse-proxy, it would have to load all the routing configuration which would introduce a lot of latency to the request;
3. On-the-fly routing changes or configs would be useless;
4. Probes to Azure Function based backends would be a cost problem, and in the end of the day useless;
5. Azure Functions host implementation and hosting model limitations makes it a bit hard to use (i.e. no proper DI, unable to change configuration sources, etc.)

If you want to go this route, there is a way... If you use Azure Functions Premium (or greater) SKU, you can put your functions project into a container (just a simple Dockerfile) and you can also inject your own custom Azure Functions Host process, which will give you more control and the ability run the reverse-proxy on it. 

In that case, most of the limitations I've mentioned of the Az Func are worked around, including the cold-start, since in that SKU, you have at least 1 _warm_ container always active (you can configure to have more) which means you don't suffer of cold-start and you still get the auto-scalling capabilities of Az Func.

Another option that I see, is if the Azure Functions team decides to "embrace" this as a feature inside the product extending the current Proxy Function functionalities to use this. That would bring you the full serverless model and at same time, abstract away the reverse-proxy deployment. This is basically what is happening with SignalR Services when they are hosting SignalR for you as a fully managed service and allow you to have backends that handle Hub method calls.

I hope that gives you a light.

**Comment by pksorensen** [comment]
@galvesribeiro I dont agree with any of your 5 drawbacks.

Azure functions runs on aspnet core and uses DI, it can also keep singleton objects across function invocations. 

So its definite possible to make it work on azure functions with the exact same benefits/drawbacks as any other app has running on azure function if the azure function team wanted to.

**Comment by galvesribeiro** [comment]
@pksorensen I didn't said it was impossible. Just saying that it is very limited and bring you drawbacks. I've been using Az Functions since its inception. If you look at the SDK/Host/Tooling repository for the issues, and search for anything related to DependencyInjection, you will see that it has a *lot* of limitations and problems that a _normal_ Asp.Net projections doesn't.

To start with, it doesn't honor the API surface from `Microsoft.Extensions.DependencyInjection.Anstractions`. That is because they have their own `IServiceProvider` implementation that rely on a custom IoC container that is very limited as you may see on many issues (just check the the WebJobs Host source code, it is OSS and you will see it is not _just_ an AspNet Core project). But that is just one topic. I could spend an 1+ hour talking about the difficulties we had when we dived into Az Functions but that is not the case. Again, it is not that the product is bad. It is just that it was not meant to support such scenarios IMHO, even if I don't agree with the design of the whole product technically speaking.

> Azure functions runs on aspnet core and uses DI, 

Again, the DI implementation is not near close to Asp.Net Core one. You can't even change things like `IConfiguration` and other infrastructure components. There are some hackery to create another DI container and then after build, re-registrer everything on the Functions one, but that has a a huge chance of overwriting the Host services already being registered which affects the way the auto-scaler work, etc, so I wouldn't go that path (believe me, I've tried).

> it can also keep singleton objects across function invocations.

Like I said, it is technically possible BUT, if you have the bad luck to get have to wait for the host to start, and even worse, if the host start is pulling the reverse-proxy (or any other) configuration from an external source (i.e. Database, Azure App Configuration, etc), you are doomed. Your performance will be hurt a lot. One of the major points on this project is to have the proxy configuration dynamically loaded AND reloaded, so you can read in production to changes based on external circumstances and that would be totally killed if you have a cold start.

> So its definite possible to make it work on azure functions with the exact same benefits/drawbacks as any other app has running on azure function if the azure function team wanted to.

Like I said, it is possible, but without bringing the proxy to the platform, in this case Azure Functions, it will not be a good thing IMHO. Look for SignalR Services as I mentioned before. If they didn't brought it _inside_ Azure as a product but instead let you send a SignalR Hub connection request directly to an Azure Function, how would maintain the statefulness? You would be basically create 1 connection per Hub method Invokation which totally blow the whole purpose of stateful connections with WebSockets.

Again, there are ways to do it. Not technically impossible. The project is very well designed and abstracted BUT, you have to take in consideration the constraints that serverless hosts bring to you. By definition, serverless functions, like Azure Functions, aren't meant to keep stateful connections. 

A reverse proxy doesn't just handle REST APIs... What about HTTP/2? WebSockets? Session/cookie Affinity? Where do you put the *state* (ofc, besides having an external state storage like Redis or something else which again, bloat the use case)?

Those are the answers that you don't have for this particular scenarion.

But again, like I said before, perhaps using the Azure Functions Premium SKU would reduce you problems with cold-start (without a custom Functions Host) or, fully account for the DI and custom configuration dependencies that I've mentioned (with a custom host in a Docker container).

**Comment by galvesribeiro** [comment]
Just to give an idea o how messy is the DI implementation on it, look at https://github.com/Azure/azure-functions-host/issues/4413 and like I said, have a look on DependencyInjection as a search in the Azure Functions related repositories and you will see that DI is a hot topic of problems on it. You can now guess why! 💃

**Comment by samsp-msft** [comment]
Running the proxy within Azure functions is not a scenario we plan to support in 1.0. Adding to the backlog to reconsider later.

**Comment by pksorensen** [comment]
I am running it on azure function now for my hobby projects, consumption plan using a wrapper.
![image](https://user-images.githubusercontent.com/2718591/94357983-d8acc980-009d-11eb-94bc-54da10874cbb.png)

The startup is all the same as a normal startup of aspnetcore app, and if a project becomes popular enough that azure functions do not performance well enough, its just a switch to deploy to a normal webapp.

Not having any of the issues @galvesribeiro is mentioning - maybe only a few extra ms overheads of running on azure function vs raw IIS.

**Comment by espray** [comment]
@pksorensen do you have a repository you could share?

**Comment by murilocurti** [comment]
> I am running it on azure function now for my hobby projects, consumption plan using a wrapper. ![image](https://user-images.githubusercontent.com/2718591/94357983-d8acc980-009d-11eb-94bc-54da10874cbb.png)
> 
> The startup is all the same as a normal startup of aspnetcore app, and if a project becomes popular enough that azure functions do not performance well enough, its just a switch to deploy to a normal webapp.
> 
> Not having any of the issues @galvesribeiro is mentioning - maybe only a few extra ms overheads of running on azure function vs raw IIS.

@pksorensen can you share a sample? I think it deserves an article :) Thanks!
