### ISSUE TITLE
Provide an async version of IProxyConfigProvider 

### ISSUE THREAD

**Issue by cecilphillip** [microsoft/reverse-proxy#429]
### What should we add or change to make your life better?
It would be helpful if there was a version of IProxyConfigProvider's `GetConfig` that returned a Task&lt;IProxyConfig&gt; or ValueTask&lt;IProxyConfig&gt;

### Why is this important to you?
When trying build configuration from a database or web api call, you end up with `GetAwaiter().GetResult();` style calls in the method body.

**Comment by Tratcher** [comment]
We've considered this but decided against it.

The first load happens during startup which is already a synchronous process that we don't control. For the first load you have the choice of returning an empty set or blocking.

All subsequent loads should take place in the background before signaling the change token so that GetConfig can return synchronously.

**Comment by cecilphillip** [comment]
@Tratcher Thanks. That makes sense. I was able to get this to work
