### ISSUE TITLE
Session Affinity

### ISSUE THREAD

**Issue by anurse** [microsoft/reverse-proxy#45]
We should support session affinity as a native feature in the proxy. It's effectively a load balancer directive. Some attribute of the incoming request is used as a key to identify which backend to route to.

Affinity logic needs to run:
* Before load balancing, to check the affinity "stamp" and select a single destination (i.e. one of the servers within a backend) (if possible)
* After load balancing, to stamp the selected destination into a cookie, if enabled.

It also may need to be able to re-trigger load balancing (in the failure modes below).

Supported "modes" (please do suggest others!):
* Cookie
	* A request with no incoming "stamp" is assigned to a destination by normal load balancing policy
	* The return response is stamped with a Cookie containing the destination ID, cryptographically signed by a key trusted by all proxy instances (DataProtection!)
	* On future requests, we validate the stamp and select the specific destination for routing
	* If that destination is no longer in the active set of destinations, we "fail" (see failure modes)
* 5-tuple (`Source IP`, `Source Port`, `Dest IP`, `Dest Port`, `Protocol`)
	* Hash the 5-tuple values and use it to identify a destination.
	* If that destination is no longer in the active set of destinations, we "fail" (see failure modes)
* Header value
	* Hash some header value and use it to identify a destination
	* Useful for auth-token based affinity (used in Azure SignalR, for example)
* ~~Crazy idea: magic SignalR mode?~~ We should track this separately, just wanted to see if anyone had C O O L thoughts here.
	* It could be cool to have native support for session affinity for SignalR connections.
	* There's a connection ID in the initial `/negotiate` response, which is also present in the query string of all future requests, which we could use for affinity.
	* This could be very useful for applications which don't generally need affinity, but also use SignalR (which requires affinity).
	* Could possibly be generalized

Failure modes
* If the session affinity system identifies a target destination which is no longer routable, a configurable failure response should be used
* Possible responses
	* Re-affinitize to one of the other destinations (i.e. re-route and stamp the new backend)
	* Return a 503 (since the target destination is no longer active)

These are mostly just my rando thoughts. I'm interested in @davidni 's thoughts, as well as the team's (@Tratcher @halter73)

**Comment by samsp-msft** [comment]
Architecture question: Some of this needs to be infrastructure to create a signed blob as part of a cookie, and some will probably be specific to the configuration of the specific site. Where that configuration is picking things like the mode for determining the host, is that something where we will have one component that has config and a couple of options, or is this where we use easy extensibility as our differentiator. 
Personally I like the concept of "its just code" to express these types of rule as a core difference from competition - as long as the code that needs to be written is short/easy/understandable. That may mean we have file-template classes, bases with virtual members for overrides, or events/delegates.

**Comment by anurse** [comment]
> Some of this needs to be infrastructure to create a signed blob as part of a cookie, and some will probably be specific to the configuration of the specific site

Well, the content of the blob is consistent and defined by the proxy, not the user (at least in general). For example, ARR has this feature natively and doesn't require code changes to enable it. What *does* need to be configured by the user is the key used to protect this information, and we have components in ASP.NET Core to do that (DataProtection).

**Comment by Tratcher** [comment]
> 5-tuple (`Source IP`, `Source Port`, `Dest IP`, `Dest Port`, `Protocol`)
> * Hash the 5-tuple values and use it to identify a backend.
> * No "failure" mode here since the backend is recomputed on each request.

What does no failure mode here mean? Can't this fail the same way as cookie if the matched backend is no longer available?

**Comment by samsp-msft** [comment]
Is the source port always the same? And if you are behind a corporate firewall do you always get the same outbound IP?

**Comment by anurse** [comment]
> What does no failure mode here mean? Can't this fail the same way as cookie if the matched backend is no longer available?

Well, my thinking is that the inputs are hashed and used to look up a backend from the set of available backends, but now that I think about it I think you're right. It would have to be a stable hash over the entire set of possible backends for that route and if it matches one that's currently offline it would fail.

**Comment by Tratcher** [comment]
> Is the source port always the same?

Source ports are random.

> And if you are behind a corporate firewall do you always get the same outbound IP?

That would be the source IP, and yes this approach would be confused by outbound proxies.

There's another level of affinity we haven't considered here. NTLM/kerberos needs connection level affinity. e.g. Requests on a specific inbound connection are mapped to requests on a specific outbound connection to a specific backend.

Do we have any evidence/requirements on which type of affinity customers want? I assume cookie and header are the main ones.

**Comment by anurse** [comment]
> > Is the source port always the same?
> 
> Source ports are random.

But in a keep-alive or HTTP/2 connection they will be the same. The 5-tuple load balancing does seem unlikely to be super useful in an L7 proxy, but I included it for completeness.

**Comment by alnikola** [comment]
I suggest to think also about the following:
1. Do we re-distribute affinity and how we do that on back-end scale-out or scale-down events (new severs get added or removed)?
2. What is an affinity TTL? Will it live indefinitely (until the target back-end is available) or expire after some time? To what extent it needs to be configurable?
3. Is "stamp" going to be bound to a source address or it can be re-used by any clients? If it's the latter, do we need some kind of throttling to avoid overloading back-end?

**Comment by Tratcher** [comment]
> * Do we re-distribute affinity and how we do that on back-end scale-out or scale-down events (new severs get added or removed)?

Affinity is needed when there's state on the destination server. We should not automatically re-affinitize unless that destination goes down or else the client will loose their state.  However, we should consider a mechanic to allow manually reafinitizing. This could be as simple as the destination deleting the affinity cookie.

> * What is an affinity TTL? Will it live indefinitely (until the target back-end is available) or expire after some time? To what extent it needs to be configurable?

That's an interesting question we should ask customers and check with other implementations. I assume it would be a session cookie that expires when the client closes the browser.

> * Is "stamp" going to be bound to a source address

Binding to a source address breaks network agility. E.g. my laptop's IP can change as I move around, but my session cookie would remain. 

> or it can be re-used by any clients?

How would they get it? It would take deliberate effort for clients to share an affinity cookie.

> If it's the latter, do we need some kind of throttling to avoid overloading back-end?

I expect we'll need throttling regardless, it's not an affinity specific feature.

**Comment by alnikola** [comment]
> That's an interesting question we should ask customers and check with other implementations. I assume it would be a session cookie that expires when the client closes the browser.

I think client can be not only browsers, but also cloud services calling backends behind reverse proxy. Then, they might either not have a session concept or not respect cookie expiration time.

> How would they get it? It would take deliberate effort for clients to share an affinity cookie.

Affinity cookie can be retrieved once by a service, put in a storage and then shared by a number of them. On top of that, a malicious client can deliberately send a huge number of requests with the same affinity cookie to overload backends.

**Comment by Tratcher** [comment]
Here's an example of using Session Cookie affinity from Azure Front Door:
https://docs.microsoft.com/en-us/azure/frontdoor/front-door-routing-methods#affinity

> I think client can be not only browsers, but also cloud services calling backends behind reverse proxy.

Yes, but browsers are a major scenario worth starting with.

**Comment by ryandle** [comment]
Hi, I'll add our reverse proxy scenario into the mix and see how it fits into your design here.

### Overview
In our service, we have a single top-level domain that all clients use (contoso.com.) We have many individual endpoints (in our terminology "service pools" - e.g. a vm scale set in Azure) deployed around the world. Customer data is bound to some subset of these pools. E.g. if you are an EU customer (tenant) then you are bound to a few of the EU pools. We maintain a mapping of customer (tenant) -> pools. 


### Top-level Domain to IP mapping
When a user makes a request to contoso.com they will hit one of the back-end endpoints (which one they hit depends on DNS resolution, which we can assume  for this conversation is geo-based. I.e. you hit the service pool 'closest' to you.)



### Failover
For a given tenant, only one of those pools they are bound to is the "primary" (accepting edits) at any given point in time. The others are replicas to be failed-over to incase there is a disaster in the primary.


### Side-by-side hosting with the Application
We run our reverse-proxy side-by-side our real web apps. On every machine backing an endpoint there is both a reverse proxy web app as well as the 'real' application web app running.

### Core Routing Logic
So for each request, we need to:

1. Examine the request (details in extraction section below) to find a route key.
    a. If no route key is found, proxy to the local application.
2. Execute custom logic to lookup (see lookup section below) the correct destination for the route key.
    a. This is usually a call into a tiered-cache we call the Route Cache (in-memory, redis, etc.) Cache misses result in a call to a more expensive lookup process where we determine which of the candidate service pools is the primary.
3. Proxy the request to that destination.

### Route Key Extraction
To find the route key on a request, we have custom logic that looks for different payload types in different locations. There are a lot of combinations due to how our scenarios evolve over time. Currently we have a mix of:

**Locations**
1. Specific Cookies
2. Specific Headers
3. Query Parameter
4. Url Path Segment

**Payload Types**
1. JWT
2. String (possibly delimited with several bits of information)

But a new scenario could come along tomorrow where we need to introduce a new location or payload type, so we need flexibility (i.e. be able to write our own C#) when extracting the route key from a request.

### Route Destination Lookup
Once we know the route key, we need to find the destination mentioned in step 2 of the above core routing logic.

The details of how we do this are all specific to our application, so I think from a requirements perspective what we need here is the ability to implement a 'lookup' interface where the input is the route key and the output is the destination.

### Response Inspection / Route Cache Clearing
I mentioned above that we cache Route Key -> Destination. When an event like failover happens we need to invalidate some or all of the route cache. This can happen a few ways:

1. Through external monitoring that decides the cache is invalid.
2. By receiving a special "Clear your cache" header in a response from a request proxied to the destination endpoint.

### Failure Modes
1. If we find a route key but can't find a destination then we 503. We need to be able to set custom headers in this case, such as Retry-After.

**Comment by Tratcher** [comment]
> Customer data is bound to some subset of these pools.

This association is pretty stable, right? You always want that customer to go to that pool, they're not dynamically assigned. In this object model that seems like a relationship to be resolved in the routing stage rather than through an affinity module. Right now there
support for static routing based on a pre-defined list of paths, hosts, headers, etc., but we also have plans for dynamic routing where you write code to directly examine the request and pick the best route/pool to assign it to (https://github.com/microsoft/reverse-proxy/issues/46).

**Comment by ryandle** [comment]
@Tratcher the list of candidate back-end pools is stable (i.e. we have ~30 back-end endpoints and they would change rarely w/ a new code deployment.) But the assignment of "this request should go to backend X" needs to be checked for every request by our routing logic. I agree it sounds like dynamic routing would work for this, I'll follow that issue. LMK if I need to add any more context or details of our scenario!
