### ISSUE TITLE
Support of forward proxy? 

### ISSUE THREAD

**Issue by mcarbonneaux** [microsoft/reverse-proxy#468]
### What should we add or change to make your life better?

Support code to support forward proxy in addition to reverse proxy. 

Need support connect method, and absolute url in http method to connect to dynamique destination in place of configurated "cluster" destination. 

### Why is this important to you?

Like reverse proxy forward proxy is very usefull building block and very near in conception.

**Comment by Tratcher** [comment]
That is not a goal we're pursuing. A forward proxy has very different requirements and needs different features (like CONNECT). There would be little or no overlap.

If you want to pursue a .NET based forward proxy you'd need to start over at https://github.com/dotnet/aspnetcore/issues/21953 to get CONNECT support.

**Comment by samsp-msft** [comment]
I am going to close this as it is explicitly a non-goal of this project to create a forward proxy.

**Comment by mcarbonneaux** [comment]
why non goal !? 
- apache httpd server (web server) support forward and reverse proxy... 
- squid cache (forward proxy cache) support forward and reverse proxy...

the only 2 thing to do is supporting connect method, and supporting dynamique target server (connection tcp to the target of connect or forward http request to the http method absolute url ...

**Comment by tbonham** [comment]
I think this would be good to have since MS has killed off the TFG and UGS products that could have been used for that. I think it should it own project and git repo.

**Comment by Tratcher** [comment]
If we were to implement forward proxying, why would you use this project's implementation rather than another? It's not clear what value we would add in that space.

There are variety of reasons we won't be implementing a forward proxy:
- Missing platform features: CONNECT isn't something we can implement directly, we need it added to the underlying platform (Kestrel). The soonest that can happen (if at all) is .NET 6, a year from now.
- Minimal overlap: About the only existing component that would be shared between a forward and reverse proxy is the IHttpProxy piece that actually does the request forwarding, and that would only work for HTTP, not HTTPS/CONNECT.
- Minimal value add: This project's goal is to add value by letting you customize how the proxy works. A forward proxy follows fairly strict standards and there's less reason to customize it. CONNECT / HTTPS tunneling also means there's less opportunity to do anything in a forward proxy as you can't inspect/manipulate the traffic, and HTTPS traffic now dominates the internet.
- Demand: Most of our customers need custom reverse proxies, very few need forward proxies.
- Focus: We need to prioritize and focus our efforts and resources.

**Comment by mcarbonneaux** [comment]
i use many reverse proxy with forward proxy with many customisation (rewrite header and boy) in my compagny. 

is very usefull to reverse proxyfy external site in internal network...

and if the need is to intercept traffic in connect tunnel you can reconnect in ssl with backend... but is more complex to implement... because you need to listen in https with dynamique certificate generated based on sni host...

and forward proxy is usefull to overcome network firewall between differente network zone...

and for kestrel CONNECT method support, seem to be supported and implemented since dotnet core 1.1... 
- [HttpMethods.IsConnect ](https://docs.microsoft.com/fr-fr/dotnet/api/microsoft.aspnetcore.http.httpmethods.isconnect?view=aspnetcore-1.1#Microsoft_AspNetCore_Http_HttpMethods_IsConnect_System_String_) used in reverse proxy code (src/ReverseProxy/Service/Proxy/HttpUtilities.cs) are supported in dotnet core >=1.1
- and [HttpMethods.Connect](https://docs.microsoft.com/fr-fr/dotnet/api/microsoft.aspnetcore.http.httpmethods.connect?view=aspnetcore-1.1) seem to be usable to like other method in proxy httputilities....

**Comment by Tratcher** [comment]
> and for kestrel CONNECT method support, seem to be supported and implemented since dotnet core 1.1...
> 
> * [HttpMethods.IsConnect ](https://docs.microsoft.com/fr-fr/dotnet/api/microsoft.aspnetcore.http.httpmethods.isconnect?view=aspnetcore-1.1#Microsoft_AspNetCore_Http_HttpMethods_IsConnect_System_String_) used in `src/ReverseProxy/Service/Proxy/HttpUtilities.cs` are supported in dotnet core >=1.1
> * and [HttpMethods.Connect](https://docs.microsoft.com/fr-fr/dotnet/api/microsoft.aspnetcore.http.httpmethods.connect?view=aspnetcore-1.1) seem to be usable to like other method in proxy httputilities....

Those are constants and helpers, the real feature implementation is tracked at dotnet/aspnetcore#21953.

**Comment by mcarbonneaux** [comment]
> Those are constants and helpers, the real feature implementation is tracked at [dotnet/aspnetcore#21953](https://github.com/dotnet/aspnetcore/issues/21953).

to transform the upstream to opaque stream...  ok
