### ISSUE TITLE
Custom error pages for offline destinations

### ISSUE THREAD

**Issue by emisand** [microsoft/reverse-proxy#471]
### What should we add or change to make your life better?
Support displaying custom content for each route or cluster while a cluster destination is offline, that means showing custom pages for HTTP 502 and 504 errors. It might be handled by a Razor Page or MVC Controller.

Currently ASP.NET Core supports handling error pages as documented here: [Handle errors in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-3.1)

What should be added is the ability to configure different error handlers for each route or cluster.

### Why is this important to you?
Showing error pages when a frontend application is down is important for the user experience, we don't want customers seeing a plain white page that only says "502 Bad Gateway".
Hosting multiple applications with the same YARP instance is a supported scenario, so I think that allowing to configure different error pages for each application handled by YARP should also be supported.

**Comment by samsp-msft** [comment]
What is the situation where all the destinations for a route will be offline - is this as part of a planned outage, or only in a disaster situation?

You should be able to catch this with an extra module in the pipeline, either to detect that there are not destinations after healthchecks, or by looking at the error code, and changing how it gets reported back to the original requester.

I am trying to weigh the importance of this feature verses others that are on the backlog?

**Comment by emisand** [comment]
@samsp-msft 
This is the main situation I want to be able to handle:
A destination in the route is restarting due to a crash, new deployment or periodic restart and the health checks didn't mark that destination as unhealthy yet. We want to show a custom error message to requests being sent to that destination.

So the scenario would be when an application is not responding but it hasn't passed enough time for the health checks to mark the destination as unhealthy.

**Comment by Tratcher** [comment]
There are a few different scenarios to consider:
A) Health checks have marked all destinations as unhealthy. YARP will refuse requests for that route/app with an empty 503.
B) The destination is completely down, YARP catches the exceptions and returns an empty 5xx (See https://github.com/microsoft/reverse-proxy/pull/406 for how errors get captured in the IProxyErrorFeature).
C) The destination responds with its own empty 5xx.
D) The destination response with a 5xx and a body.

From a middleware's perspective the first three look the same and can be handled the same. D is the hard one since you have to suppress the original response body, let's leave that aside for now.

The [StatusCodePages](https://github.com/dotnet/aspnetcore/blob/4aa7418e6c7ebcb96d6de28d25b901df6d8a787d/src/Middleware/Diagnostics/src/StatusCodePage/StatusCodePagesExtensions.cs#L179-L215) middleware is the basic outline for what you want for the first three situations. The main trick is to preserve the prior route/cluster data so you can produce a custom error page accordingly. The cluster data would still be [available](https://github.com/microsoft/reverse-proxy/blob/6311df4abe1ce10c6274c5212600011886cac2c6/src/ReverseProxy/Middleware/DestinationInitializerMiddleware.cs#L62-L66) on the IReverseProxyFeature when you were re-routed to the error page so you should be able to retrieve the information you want from there.

**Comment by emisand** [comment]
@Tratcher thanks for the details.
Looks like retrieving the `IReverseProxyFeature` from `HttpContext` when handling an error page with the StatusCodePages middleware is the way to go.

Looks it provides enough information to render the appropiate error message depending on the Cluster associated to the request.

I will test using it and give you an update if I find any issue.

**Comment by karelz** [comment]
Triage: Looks answered. Let us know if not and we can reopen. Thanks!
