### ISSUE TITLE
Documentation: not all "Improve this Doc" links are working

### ISSUE THREAD

**Issue by PieterBoeren** [microsoft/reverse-proxy#515]
### Describe the bug
Minor issue, but not all "Improve this Doc" links on the documentation (https://microsoft.github.io/reverse-proxy/articles) are working, those links resolve to a 404.

### To Reproduce

- Go to urls below and click the "Improve this Doc":

1. https://microsoft.github.io/reverse-proxy/articles/configfiles.html
2. https://microsoft.github.io/reverse-proxy/articles/configproviders.html
3. https://microsoft.github.io/reverse-proxy/articles/header-routing.html
4. https://microsoft.github.io/reverse-proxy/articles/transforms.html

**Comment by Tratcher** [comment]
Ah, yes. Those links include names of PR branchs that have been deleted.

A) We should be more careful about this when we re-generate the docs for preview 7.  E.g. do the rebuild while the branch is set to master or release, and then create the new PR branch. @alnikola I'm assigning this to you since you're shipping preview 7.
B) This should be temporary until we get #428 fixed, hopefully soon after .NET 5 ships next week. Then the builds will all happen on the CI on controlled branches.
