### ISSUE TITLE
[SF] Service Fabric integration should support more than one endpoint/listener per service

### ISSUE THREAD

**Issue by mcpride** [microsoft/reverse-proxy#541]
### What should we add or change to make your life better?

The Service Fabric integration for dynamic discovery of routes PR #257 would help us a lot. But it should support more than 1 endpoint / listener per service because  a Service Fabric service can provide more than one endpoint.

### Why is this important to you?

A SF service could provide different public api's on different ports e.g. an additional management or administration api (especially 3rd-party guest apps which can't be easily decomposed to different services).

See discussion: https://github.com/microsoft/reverse-proxy/pull/257#issuecomment-726649119

**Comment by akanieski** [comment]
Perhaps it makes sense to align Yarp Clusters with a combination of SF.Service and SF.Endpoint?

So endpoints would end up more in line with Yarp Cluster, instead of just a given service. And like you said, it means we'd have to move routes under a given endpoint.

```
Yarp Cluster -> fabric:/App1/Svc2/WebInterface
                    -> https://10.1.1.5:30001
                    -> https://10.1.1.6:30002
                    -> https://10.1.1.7:30003

Yarp Cluster -> fabric:/App1/Svc2/AdminInterface
                    -> https://10.1.1.5:30004
                    -> https://10.1.1.6:30005
                    -> https://10.1.1.7:30006
```
I think this makes sense from what I understand.  

About using XML to define that structure. There are alot of similarities between orchestrators. Most of the orchestrators support at least some sort of string label/tag. I'm working on a Docker auto-discovery right now for Yarp and I was able to largely re-use the LabelsParser from #257. We should likely refactor that out into a common namespace for folks who intend to implement configuration providers. 

With that in mind, I tend to lean towards using `Dictionary<string, string>` with Labels instead of XML.

**Comment by karelz** [comment]
Triage: We should timebox investigation into a design to see if it changes current design significantly. Otherwise Backlog.

**Comment by Tratcher** [comment]
SF work has moved to https://github.com/microsoft/service-fabric-yarp
