### ISSUE TITLE
Proxy supplies metrics for monitoring performance

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#61]
Collect metrics for all stages of the proxy processing, including outbound http requests

**Comment by samsp-msft** [comment]
@davidsh - if you have existing issues in the dotnet repo, we should tag those here, and they will appear in the board(s)

**Comment by anurse** [comment]
Whoops, I created #63 and missed this. I'll add my expanded info to this and close #63.

**Comment by anurse** [comment]
In order to provide the detailed diagnostics proxy users will want, we need to expand the diagnostics and tracing support throughout the networking stack.

This includes both counters (using `EventCounters`) and tracing (using `EventSource`). It covers the low-level sockets API, as well as higher level APIs like HttpClient.

Another aspect to consider here is dimensions. We believe it is important for users to be able to specify the "scope" of a particular network operation and include custom dimensions like Route identifiers, backend names, etc. For v1 we believe it is sufficient to express these in the EventSource events, and keep the counters high-level.

**Comment by davidsh** [comment]
Linking: https://github.com/dotnet/runtime/issues/37428

**Comment by samsp-msft** [comment]
Q: How to add structured info to the log entries. How to track timing for sub tasks within the flow of processing a request.

@samsp-msft to send docs from Vance to David to see if the event source activity work.

**Comment by karelz** [comment]
@samsp-msft as discussed, can you please check if we have all requirements for E-Core3?

**Comment by MihaZupan** [comment]
@samsp-msft Is there anything left in this issue?

**Comment by MihaZupan** [comment]
@samsp-msft can this be closed against #676 as only missing documentation, or is there something else you had in mind?

**Comment by karelz** [comment]
Triage: @samsp-msft says it can be now closed :)
