### ISSUE TITLE
Investigate content headers being dropped when content-length is 0

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#618]
In theory you can have a POST request with a Content-Length: 0, but still have other content headers like Content-Type which would be used for routing the request at the destination. 

In today's HttpProxy logic we avoid creating the HttpContent on the request if there's no body since HttpClient will automatically create a chunked body for any HttpContent without a specified length (and a servers treat requests like GETs with a chunked body as invalid). We may need to special case zero length bodies and provide an empty content object so that we can still forward headers like Content-Type (would HttpClient allow that?).

**Comment by karelz** [comment]
Triage: See also customer report #875

**Comment by Tratcher** [comment]
The problem is here where we avoid making a HttpContent object if we don't think there's a body:
https://github.com/microsoft/reverse-proxy/blob/293dbce4c032d9a8558b5f0bbcd26e78451ec87b/src/ReverseProxy/Service/Proxy/HttpProxy.cs#L307

And here, where we don't copy content headers if there is no body:
https://github.com/microsoft/reverse-proxy/blob/293dbce4c032d9a8558b5f0bbcd26e78451ec87b/src/ReverseProxy/Utilities/RequestUtilities.cs#L81-L84

**Comment by MihaZupan** [comment]
Observations:

The problem is the difference between `has content bytes (body)` and `has content headers`. A request may have content-specific headers even without a body. `HttpClient` will only accept such headers on the `HttpContent`, forcing us to set one even if there is no body.

In cases where there is no body, we are currently dropping the following headers:
- Allow
- Content-Disposition
- Content-Encoding
- Content-Language
- Content-Length
- Content-Location
- Content-MD5
- Content-Range
- Content-Type
- Expires
- Last-Modified

That is, all headers HttpClient considers as "known" and which are marked with `HttpHeaderType.Content` - see [KnownHeaders](https://github.com/dotnet/runtime/blob/c90debb5dc8ee85840bbef1a44b8502ab169f47b/src/libraries/System.Net.Http/src/System/Net/Http/Headers/KnownHeaders.cs#L28-L61).

One way we could fix this is in the [`AddHeader`](https://github.com/microsoft/reverse-proxy/blob/b36e3ce34161559a1e0207fa2b8b03cff58ca4c8/src/ReverseProxy/Utilities/RequestUtilities.cs#L88) helper:
- If `request.Headers.TryAddWithoutValidation` returns false and there is no content set, check if we are dealing with one of the above headers
- If we are, set an `EmptyHttpContent` that implements `TryComputeLength` (returning length = 0, true) to avoid `HttpClient` defaulting to chunked encoding

The upside to doing it in the `AddHeader` helper vs in [`SetupRequestBodyCopy`](https://github.com/microsoft/reverse-proxy/blob/b36e3ce34161559a1e0207fa2b8b03cff58ca4c8/src/ReverseProxy/Service/Proxy/HttpProxy.cs#L331) is that it will apply to any custom headers set by users in transforms, not just the headers we received.

The overhead should also be minimal as we are only doing work in the case of above mentioned headers and no content being set.

@Tratcher thoughts?

**Comment by MihaZupan** [comment]
One theoretical case we can't handle with HttpClient is if a user wants to send one of the headers mentioned above while sending neither `Content-Length` nor `Transfer-Encoding`

**Comment by Tratcher** [comment]
> One theoretical case we can't handle with HttpClient is if a user wants to send one of the headers mentioned above while sending neither `Content-Length` nor `Transfer-Encoding`

You mean that HttpClient would add a `Content-Length: 0` header for the new EmptyHttpContent? That's acceptable.

IIS and Kestrel currently refuse POSTs that are missing a Content-Length or Transfer-Encoding header. Kestrel only removed that requirement in 6.0.

**Comment by Tratcher** [comment]
Try the proposed fix and we'll see how it works.

We should add a check for `Content-Length` other than 0 in this situation, as that would indicate our body detection logic was wrong.

**Comment by MihaZupan** [comment]
> You mean that HttpClient would add a Content-Length: 0 header for the new EmptyHttpContent? That's acceptable.

Yes, but for any method (including GET), if someone sends a header like `Content-Type`, we will inject either `Content-Length: 0` or `Transfer-Encoding: chunked`.

> We should add a check for Content-Length other than 0 in this situation, as that would indicate our body detection logic was wrong.

I assume you mean debug-only?

**Comment by Tratcher** [comment]
I'm not sure what kind of check. An exception might be warranted because sending a non-zero content-length header with an empty body would be a protocol violation.
