### ISSUE TITLE
Rename X-Forwarded-PathBase to X-Forwarded-Prefix

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#737]
Follow up to #225 and #13.

Per some user provided research [here](https://github.com/dotnet/aspnetcore/issues/23263#issuecomment-776192575), `X-Forwarded-Prefix` is the more common name for this header.

/cc: @damianh

**Comment by damianh** [comment]
Interesting...thx for cc. Searching up on this and most of the `X-Forward-Prefix` content (SO questions, docs in various proxies etc) seems to be a recent thing (last couple of years). I've reckon I've been using `X-Forward-PathBase` for nearly a decade... 🤷‍♂️

Since a variety reverse proxy implementations are converging on `X-Forward-Prefix` I agree that renaming is reasonable.

On a related item, will `Microsoft.AspNetCore.HttpOverrides` also be updated to use this header? If so, I could kill off [this project](https://github.com/ProxyKit/HttpOverrides) :)

**Comment by Tratcher** [comment]
> On a related item, will `Microsoft.AspNetCore.HttpOverrides` also be updated to use this header?

https://github.com/dotnet/aspnetcore/issues/23263 tracks that.

**Comment by karelz** [comment]
Triage: There is de facto standard for this (see https://github.com/dotnet/aspnetcore/issues/23263#issuecomment-776192575), we should implement it.

**Comment by karelz** [comment]
Should be fairly simple - anyone interested?
