### ISSUE TITLE
Pass CancellationToken to HttpContent.ReadAsStreamAsync for .Net 5.0

### ISSUE THREAD

**Issue by Kahbazi** [microsoft/reverse-proxy#770]
A new overload for `HttpContent.ReadAsStreamAsync`  is introduced in .Net 5.0 which gets `CancellationToken`. Should it be used?

https://github.com/microsoft/reverse-proxy/blob/b734f195b55d0ba623caf88262342d9068402042/src/ReverseProxy/Service/Proxy/HttpProxy.cs#L481
https://github.com/microsoft/reverse-proxy/blob/b734f195b55d0ba623caf88262342d9068402042/src/ReverseProxy/Service/Proxy/HttpProxy.cs#L533

**Comment by Tratcher** [comment]
@ManickaP the HttpContent on the response always synchronously returns a stream, right? The CT wouldn't be used?

**Comment by MihaZupan** [comment]
For built-in ones it will, but a custom `HttpContent` may end up doing async work.

We could also do a type check for `SocketsHttpHandler` and call the sync API here to save the Task<Stream> allocation.

**Comment by ManickaP** [comment]
> the HttpContent on the response always synchronously returns a stream, right? The CT wouldn't be used?

Yep, the CT is not used, response content returns stream synchronously:
https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionResponseContent.cs#L77-L78

> We could also do a type check for SocketsHttpHandler and call the sync API here to save the Task allocation.

:+1: Since overriding response content is highly unlikely (returned by the client) we could just call synchronous [`ReadAsStream`](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Http/src/System/Net/Http/HttpContent.cs#L284) in those two places

**Comment by karelz** [comment]
Triage: Once we drop 3.1 support, we should just do it. #ifdef-ing the code now is not worth the effort.

**Comment by samsp-msft** [comment]
Should discuss lifetime of 3.1 support now that .NET 6 with LTS is shipped.

**Comment by karelz** [comment]
Triage: Likely not in 1.1 of YARP. It is also major breaking change (technically).

**Comment by samsp-msft** [comment]
Related to #1727
