### ISSUE TITLE
Design  code driven dynamic proxy routing

### ISSUE THREAD

**Issue by anurse** [microsoft/reverse-proxy#8]
There are 3 ways I can see routes being defined for a proxy:
**a)** In config via a config file, changeable at runtime - this is what most proxies do today
**b)** Statically defined in code - setting up static endpoints similar to the sample [startup.cs](https://github.com/dotnet/proxy/blob/60300714acb69cd6a7c3122c69dd7ccf517e5cea/src/sample/Startup.cs#L42-L44)
**c)** Dynamically created by code. This seems to be what most of the Azure partners need. At startup, and periodically the code will need to query a backend to fetch both the Endpoints to listen to, and where each of those should be routed.
_[added from discussion below]_
**d)** When there are too many routes to load them all, we need to be able to query a database per request to load and cache routes. From our research, more Azure partners do this than C.

This last bucket is where we need to shine and differentiate ourselves from the competition.
It will need to account for:
- Listening on new IP Addresses / ports
- SNI and being able to dynamically lookup a cert based on the client hello
- route based on the hierarchy of the URI path & query string

For some apps, they may need to do a DB lookup to discover the cert/route based on the URL being passed - so will need to have a cache and fallback mechanism.

Performance would dictate you probably need optimized structures like a trie, that I suspect are behind the existing routing tables. Either we need APIs to be able to dynamically edit the tables, and/or create and replace the tables, or be able to use the same concepts from custom app code for the proxy.

**Comment by Tratcher** [comment]
d) When there are too many routes to load them all, we need to be able to query a database per request to load and cache routes. From our research, more Azure partners do this than C.

My initial prototyping shows that we'd need to bypass the normal route table entirely and add an alternate endpoint resolution middleware that queried the database (& cache) per request to identify the correct route.

It's unclear if this could be implemented efficiently for path based routes when wildcards are involved. Strong host matches, and single level host wildcard matches seem like the best match for this scenario. That said, we'd probably provide a very generic dynamic endpoint lookup abstraction here and the efficiency would be a concern for the implementer.

**Comment by rwkarg** [comment]
I'm really excited by what appears to be option c) above to enable multi-cluster k8s ingress, whether by having cluster and ingress discovery as a custom code component in the reverse-proxy itself or by having the clusters run a separate component to push ingress information to a central store and the reverse-proxy periodically pulls from there.

Having guidance on what the specific, supported seam is to insert that periodic updating of the Endpoints and Destinations would be appreciated.

It would defiantly be a background pull and update like c) as opposed to a routing-time query like d).

**Comment by Tratcher** [comment]
@rwkarg our initial focus will be on making sure we provide the infrastructure and APIs to add and remove routes/backends/destinations through code. I expect it to work a lot like the current config based provider where something listens or polls for an external change event, reloads data, and notifies the core proxy that there's a new set of routes/etc available.
https://github.com/microsoft/reverse-proxy/blob/4a5b06bd6305ba501bfd0dc2a57fdc9aa98a5ff1/src/ReverseProxy/Configuration/ProxyConfigLoader.cs#L66-L67

**Comment by cecilphillip** [comment]
@Tratcher would d) enable integration into a service like [consul](https://www.consul.io/) for dynamically registering backends?

**Comment by Tratcher** [comment]
@cecilphillip d is purely code driven, it could integrate into just about anything.

**Comment by rwkarg** [comment]
c) sounds like it's just remote config. We have a set of routes or backends in something external to the local Configuration that we want to periodically sync from (Consul, database, kubernetes ingress).
This seems achievable right now with a `BackgroundService` that updates the `IBackendsRepo` and/or `IRoutesRepo` and then calls `IReverseProxyConfigManager.ApplyConfigurations` if there has been a change on the remote config. There may be a better/more supported method, but this does work.

d) is a case where there is either 
 - no "full state" of the potential routes and backends and it needs to be computed at request time instead of extracted from config (local or remote).
 - a "full state" exists but there is a desire to not sync all of it as in case c); likely because the "full state" is too large or is much larger than the actual working set that will be needed by the proxy.

**Comment by mj2015** [comment]
Option C is what I currently have a custom reverse proxy for - but it is reactive rather than configured. What we have is a http://server/[GUID]/api/something call that goes into the reverse proxy, and the reverse proxy looks up the GUID in its cache and if it is not there, it makes a quick call to find out the IP of the server it should pass it to, taking out the GUID on the way. The cache is auto-cleared after a while because if it is still needed, it will be available again from the function that knows the relationships. Worth saying perhaps that the servers are containers created on demand for a single user to link to in a stateful manner. This is not the usual dynamic scaling.

So fundamentally, the ideal of having a function that can be called to determine the destination for every request, and possibly change the path as well, would fit our needs perfectly. If the function returns "false" then normal routing configuration would be applied.

**Comment by Tratcher** [comment]
https://github.com/microsoft/reverse-proxy/pull/1277 just implemented query based routing. It hasn't shipped in a preview yet but is available from our daily builds. https://github.com/microsoft/reverse-proxy/blob/main/docs/DailyBuilds.md
