### ISSUE TITLE
Interrupt and replace proxy response

### ISSUE THREAD

**Issue by maknapp** [microsoft/reverse-proxy#821]
### What should we add or change to make your life better?
It would be useful to be able to cancel sending the proxy response back and optionally send a different response.

### Why is this important to you?
I need to watch 302 Forward headers from the proxy response, and if they match certain criteria, send back a 200 text/html response with a notice and the link so that if the user did actually intend to navigate there they need to click the link. I got this working currently by doing the response in `TransformResponseAsync`, relying on the proxy failing with "response has already started" error. It works but is certainly not a great solution.

**Comment by samsp-msft** [comment]
Hmm, we don't have a good story for that today, or a suitable callback in the middle of ProxyAsync. @Tratcher, this opens a can of worms for what you could do in terms of rewriting the response. 
Even though this ask is for looking at response headers, it feels like a slippery slope to wanting to have a buffered request/response where additional logic can process and manipulate the body that is sent in either direction.

**Comment by maknapp** [comment]
I am currently testing the migration from ProxyKit. I just realized manipulating the response body is also a requirement of mine - some proxy destinations are old and return HTML with URLs that are not proxy-friendly. In this case, I know which requests will need rewriting before proxying and can buffer only those.

Maybe add two forward/respond functions to split `IHttpProxy.ProxyAsync` for manual control (similar to ProxyKit)?

**Comment by samsp-msft** [comment]
I think a different version of ProxyAsync is what is needed here. Probably something like BufferedProxyAsync that then takes callbacks to modify the request and response as they both pass through. 
Its not going to be as performant as non buffered, but for specific scenarios, its what is needed. This would also allow for retry and mirroring scenarios.

**Comment by Tratcher** [comment]
I've started trying to break up IHttpProxy.ProxyAsync into more distinct steps, but the complexity it adds is significant. It also doesn't help people using the rest of the proxy APIs.

One alternative I'm considering is to change TransformResponseAsync to return a bool that would let you short circuit the remainder of ProxyAsync (e.g. copying the body and trailers).
https://github.com/microsoft/reverse-proxy/blob/aa770a88d000db1b63d35089fc0d31dd267cdea7/src/ReverseProxy/Service/Proxy/HttpTransformer.cs#L69

That would allow you to send an alternate response in the callback, or you could wait until after ProxyAsync completes and check HttpResponse.HasStarted.

This approach could work for the higher layer structured transforms as well, adding a similar bool to [ResponseTransformContext](https://github.com/microsoft/reverse-proxy/blob/aa770a88d000db1b63d35089fc0d31dd267cdea7/src/ReverseProxy/Service/RuntimeModel/Transforms/ResponseTransformContext.cs#L12). In that case I'd recommend putting the custom response in middleware so that the remaining transforms would have a chance to run without hitting an error about the response having already been sent.

**Comment by maknapp** [comment]
Returning a bool for `TransformResponseAsync` would work, but it seems a little ambiguous to me.

I suggested two separate functions instead of callbacks because I need to do database queries with my response rewriting. To reduce queries, I only make them after the proxied response returns with a 200 and text/html content type. With everything being in a transformer, I need to make a new transformer for each request with the DbContext, logger, etc.... Two separate proxy functions would simplify my transformer and make the proxy flow more readable.
```c#
using var response = await httpProxy.SendToDestination(context, ...);
if (CheckSomething(response))
{
  // Write different response to httpContext
}
else
{
  await httpProxy.SendToClient(response);
}
```


---
Also, I did get content rewriting working with the current release by just replacing the `HttpResponseMessage.Content` inside `TransformResponseAsync`. Not sure if there is anything bad with this or not.

```c#
var content = new StringContent(body, Encoding.UTF8, "text/html");
httpContext.Response.ContentLength = body.Length;
proxyResponse.Content?.Dispose();
proxyResponse.Content = content;
```

**Comment by Tratcher** [comment]
@maknapp replacing the response body like that should be fine, especially since you're careful to dispose the old one. You'll want to make sure you do the replacement before headers are copied though. Note trying to do the same for the request body would cause a problem, we track the request body more closely with a custom HttpContent type.

___

> I suggested two separate functions instead of callbacks because I need to do database queries with my response rewriting. To reduce queries, I only make them after the proxied response returns with a 200 and text/html content type. With everything being in a transformer, I need to make a new transformer for each request with the DbContext, logger, etc....

The transformer has access to the HttpContext and would be able to get the DbContext, logger, etc. itself, you don't need a new one per call. TransformResponseAsync would also let you inspect the status code and content type. I assume that's how you got the body replacement working above.
___

I've tried breaking down HttpProxy into composable calls to enable:
A) Caller control flow
B) Request and response transformations without callbacks

It ends up being four steps, each with :
1. Create the request
2. Send the request
3. Send the response
4. Complete the response

https://github.com/microsoft/reverse-proxy/commit/90d7d04a73c8bad626138ea8714748dc3124a06c#diff-0a4324a1a2cfc979ba03a1cd37836a44d3184f221cf82a121cad58dac3423d3bR118-R128

Request transformations happen between steps 1 and 2, response transformations between 2 and 3, and trailer transformations between 3 and 4. Step 4 primarily exists for gRPC streaming scenarios.

Here are some of the challenges I see with this approach:
A) It makes the simple case harder. If I don't want to customize anything why should I have to go through all of these steps? Should there be a top level wrapper around these for the simple case?
B) Similarly, the excepted usage is less discoverable. It will require a lot of docs to explain how to use these together, which are optional, etc..
C) The caller becomes responsible for the lifetime of the HttpResponseMessage, which if no properly disposed could cause a resource leak or worse.
D) Steps 2-4 can fail so the caller has to check each for success before continuing. We don't want this component to throw for common failures, that's why we have the ProxyError enum instead.
E) We need a way to flow state between the calls. I've added state into the HttpRequestMessage.Options/Properties collection which may not be recommended. Using this collection also adds extra allocations per request.
F) We'll have to re-design the telemetry model. If the caller chooses not to move onto step 3, our telemetry has no way of identifying the end of that request.

We'll discuss this more in our next team meating.

**Comment by Tratcher** [comment]
Here's a quick look at an alternative I proposed [above](https://github.com/microsoft/reverse-proxy/issues/821#issuecomment-797099978):
Direct proxy - Allow the transform callback to return false to short circuit the remainder of the processing.
https://github.com/microsoft/reverse-proxy/commit/8eb197564f2a2af8e071beb1730a2484a359331a#diff-864e9f675b0f53707e74be0e99181f657646b2b33a6f75f04f94b3715181ffc1R81-R91
General proxy - Allow structured transforms to set a property to short circuit the remainder of the processing (though not the other transforms?).
https://github.com/microsoft/reverse-proxy/commit/8eb197564f2a2af8e071beb1730a2484a359331a#diff-626186537c38320a01a7715686741c1f818b078a7e933ab1045537d17f3a0e97R77-R87

This approach is much simpler and almost as powerful. It avoids most of the error handling, lifetime, and telemetry issues encountered in the multi-step model.

Thoughts?

**Comment by maknapp** [comment]
This makes me lean towards the short circuit simple solution. I cannot come up with any use-cases where the 4 step solution would be the only solution (but someone will probably have one right after going with the short circuit solution).

A wrapper for the simple case would initially cover B, C, and D by giving an example to work from. Would the 4 step solution make any of the other open issues/enhancements easier to accomplish (load balancing, retries, etc.)?

**Comment by Tratcher** [comment]
> Would the 4 step solution make any of the other open issues/enhancements easier to accomplish (load balancing, retries, etc.)?

A decomposed API doesn't benefit the higher level middleware pipeline at all, only direct callers. Load balancing happens before proxying and is unaffected by either approach. Retry needs to suppress the response, but could be done with either mechenismn.

The most interesting scenario for the decomposed API is that it decouples the transform model, which is something we've thought about in the context of integrating IHttpProxy directly into Asp.Net Core.

**Comment by bbhxwl** [comment]
Garbled?


```

public class CustomTransformer : HttpTransformer
{
    public override async ValueTask TransformRequestAsync(HttpContext httpContext, HttpRequestMessage proxyRequest, string destinationPrefix)
    {
       // return base.TransformRequestAsync(httpContext, proxyRequest, destinationPrefix);
        await base.TransformRequestAsync(httpContext, proxyRequest, destinationPrefix);
        proxyRequest.Headers.Host = null;
    }
    public override async ValueTask<bool> TransformResponseAsync(HttpContext httpContext, HttpResponseMessage? proxyResponse)
    {
  
       string body=await proxyResponse.Content.ReadAsStringAsync();
        body= body.Replace("<title>Vue.js</title>", "<title>bbhxwl</title>");
        var content = new StringContent(body, Encoding.UTF8, "text/html");
        httpContext.Response.ContentLength = body.Length;
        proxyResponse.Content?.Dispose();
        proxyResponse.Content = content;
        return await base.TransformResponseAsync(httpContext, proxyResponse);
    }

}
```
![image](https://user-images.githubusercontent.com/26525599/141882755-c7964959-4eeb-42f2-b3f1-922022eabe5d.png)

**Comment by Tratcher** [comment]
Comments on closed issues are not tracked, please open a new issue with the details for your scenario.
