### ISSUE TITLE
ProxyRoute/ClusterInfo accessible via HTTP HttpContext extension methods

### ISSUE THREAD

**Issue by siby-george** [microsoft/reverse-proxy#836]
### What should we add or change to make your life better?
Have an public extension method for accessing ProxyRoute from http context
### Why is this important to you?
We want to build Authorization Policy which picks claims/roles from ProxyRoute.Metadata to make Authorization configurable.
This also help in accessing this information in custom Middleware

**Comment by Tratcher** [comment]
These were just made public:
https://github.com/microsoft/reverse-proxy/pull/814/files#diff-50ec618d1c9cc9d3845f1507263b0dfc1f12216da468f6743fba0ac6e3866d67

You can try them out using the daily builds: https://github.com/microsoft/reverse-proxy/blob/main/docs/DailyBuilds.md

Fair warning, there's more churn in the daily builds right now due to branding changes #811.

**Comment by samsp-msft** [comment]
Closing as PR #814 has been merged.
