### ISSUE TITLE
Ensure that connection related headers are stripped out as part of proxying

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#877]
There are potential attacks of proxies using H2c smuggling. These can occur when the proxy treats the request as http 1.1, but passes on headers that tell the destination to upgrade to h2c. Once established, there is then a channel between the client and destination server that can have multiple requests passed through it, bypassing rules implemented by the proxy.

See https://labs.bishopfox.com/tech-blog/h2c-smuggling-request-smuggling-via-http/2-cleartext-h2c for more details.

The fix is to ensure that the proxy will remove related headers to make sure that they don't get passed through. Headers we should filter include:
[ ] Upgrade
[ ] Http2-settings
[ ] Connection

This needs to be considered as part of transform rules for pipeline use and with the direct proxy.

**Comment by Tratcher** [comment]
Overlaps with #439

YARP's vulnerability to this issue would be mitigated by a few different existing factors.

A) Protocol transitions. We default to HTTP/2 connections to the destinations, and only automatically downgrade to HTTP/1.1 for WebSocket and SPDY upgrades. An H2C upgrade wouldn't be allowed if we negotiated an HTTP/2 connection over TLS + ALPN, or if we initiated a prior-knowledge (https://tools.ietf.org/html/rfc7540#section-3.4) connection to the destination. Anyone that specified HTTP/1.x or non-TLS for destinations could still be affected.
https://github.com/microsoft/reverse-proxy/blob/293dbce4c032d9a8558b5f0bbcd26e78451ec87b/src/ReverseProxy/Service/Proxy/HttpProxy.cs#L273-L286

B) H2C upgrades (https://tools.ietf.org/html/rfc7540#section-3.2) are not as widely supported by destination servers. This is not directly supported by Kestrel, Http.Sys, or IIS. Nor is it supported by most clients or browsers. The researcher had to write their own client to demonstrate the issue. I'd be curious to see which servers do support h2c upgrades and which have them enabled by default. None are named in the report. The report focused exclusively on proxies. @JamesNK most gRPC services use prior knowledge rather than H2C upgrades, correct?

**Comment by JamesNK** [comment]
As far as I know, no gRPC client uses H2C upgrades. Everyone uses either:
* HTTP/2 via TLS ALPN negotation, or
* H2C prior knowledge

**Comment by Tratcher** [comment]
@alnikola do you consider this complete after your recent changes?

**Comment by alnikola** [comment]
Not yet. We agreed to review `HTTP2-Settings` before adding it on the removal list, so this header is NOT yet stripped out.

**Comment by alnikola** [comment]
- `HTTP2-Settings` is covered by #1112
- `Upgrade-Insecure-Requests` is covered by #1115
