### ISSUE TITLE
Design proxy route config format

### ISSUE THREAD

**Issue by anurse** [microsoft/reverse-proxy#9]
Config based proxies are common and we'll need to support at least basic proxy scenarios from config. Here are some initial considerations:
- Define routes based on host and/or path
- A restart should not be needed to pick up config changes
- You should be able to augment a route with code/middleware. Kestrel does something similar using named endpoints.
- List multiple back-ends per route for load balancing
- Configure a load balancing strategy

**Comment by Tratcher** [comment]
Feedback from https://github.com/microsoft/reverse-proxy/pull/47#discussion_r418632319
> Without looking through the implementation, it's not clear why the Action takes a string. It looks like it's for the Backend id. Would it be better to put an id property on Backend similar to what we do for ProxyRoute?

This is a reflection of the asymmetry we have in the config structures. Backends is a set of named objects (with the names on the outside), but routes are an array of objects where the name is a field. There was some concern that routes needed to be specifically ordered because of how route matching works, but backends weren't considered ordered and named objects made the config cleaner. We haven't yet decided if consistency is needed here.
```
"Backends": {
      "backend1": {
        "LoadBalancing": {
          "Mode": "Random"
        },
        "Endpoints": {
          "backend1/endpoint1": {
            "Address": "https://localhost:10000/"
          },
          "backend1/endpoint2": {
            "Address": "http://localhost:10010/"
          }
        }
      },
      "backend2": {
        "Endpoints": {
          "backend2/endpoint1": {
            "Address": "https://localhost:10001/"
          }
        }
      }
    },
    "Routes": [
      {
        "RouteId": "backend1/route1",
        "BackendId": "backend1",
        "Match": {
          "Methods": [ "GET", "POST" ],
          "Host": "localhost",
          "Path": "/{**catchall}"
        }
      }
    ]
```

**Comment by Tratcher** [comment]
Discussion notes from the above feedback: We can keep the config structure as is and update the Backend and Endpoint classes to have a field for their IDs so it's more consistent with Routes when you're working with them in code. We just have to do a little fixup after the default config binding to set the id fields.

That should be the last item to address in this config epic.
