### ISSUE TITLE
Support multiple configuration sources

### ISSUE THREAD

**Issue by mmosca** [microsoft/reverse-proxy#979]
### What should we add or change to make your life better?
The current implementation of IProxyConfigProvider is registered as a singleton service, which prevents the use of multiple configuration sources.

Registering a custom programatic source prevents the use of the configuration file.

### Why is this important to you?
Having multiple configuration sources could allow us to have a set of default Routes / Clusters on the appsettings.json while we perform programatic configuration on a second implementation of IProxyConfigProvider.

It may also allow for overriding some Routes/Clusters with less destinations for Debugging/Developer workflow.

**Comment by Tratcher** [comment]
This came up when we designed `IProxyConfigProvider` and `ProxyConfigManager`. It wasn't a priority for v1, but we did map out how it might be enabled in the future.

The singleton registration isn't a problem, the main limitation right now is that ProxyConfigManager only resolves one IProxyConfigProvider. If that were changed to `IEnumerable<IProxyConfigProvider>` then there shouldn't need to be any more DI changes.

Open questions:
- Would each provider need to be self-contained? Or could you mix and match with routes from one provider referencing clusters from another?
- What if there are conflicts between providers?
- Making sure reloads could be managed safely & efficiently. E.g. do we re-query all providers when one signals a change? How do we properly detect removals without querying all providers?
- What if there are validation errors in the data from one provider?

> It may also allow for overriding some Routes/Clusters with less destinations for Debugging/Developer workflow.

Can you give an example for this?

**Comment by ldematte** [comment]
I am facing a similar issue.
At first I said to myself: no big deal, I'll just throw in a composite, like
```cs
services.AddSingleton<IProxyConfigProvider>(sp =>
            {
                return new CompositeProxyConfigProvider(new [] {
                    new ConfigurationConfigProvider(sp.GetService<ILogger<ConfigurationConfigProvider>>(), config, sp.GetService<ICertificateConfigLoader>()),
                    new ImmutableProxyConfigProvider(GetRoutes(), GetClusters())
                });
            });
```
The idea was for the composite to expose an ``IProxyConfig`` with routes and clusters that are a concatenation of the two (optionally reporting errors for duplicates etc.)
It's not a general solution (no idea how to deal with the change token, but in my case is always the null one), but nevertheless it's not possible because ``ConfigurationConfigProvider`` is internal. 

Is there a reason why is it so? Wouln't it be better to have it public to allow more scenarios (like this one?)

**Comment by Tratcher** [comment]
> `ConfigurationConfigProvider` is internal.
> 
> Is there a reason why is it so?

There hadn't been a need for it yet. We try to keep infrastructure types internal so we can update their API as needed without breaking people.

The composite config provider is an interesting idea. Feel free to download the repo and do some more experimenting. If you can show the composite idea works then that will be a good reason to make ConfigurationConfigProvider public.

**Comment by samsp-msft** [comment]
How hard is this to do by having a single config provider that then manages and calls out to further child providers? It would then be responsible for managing collisions, and coordinating updates when multiple sub-providers are in flux.

**Comment by ldematte** [comment]
> > `ConfigurationConfigProvider` is internal.
> > 
> > Is there a reason why is it so?
> 
> There hadn't been a need for it yet. We try to keep infrastructure types internal so we can update their API as needed without breaking people.
> 
> The composite config provider is an interesting idea. Feel free to download the repo and do some more experimenting. If you can show the composite idea works then that will be a good reason to make ConfigurationConfigProvider public.

It totally makes sense, I do the same on my code, trying to expose just interfaces and not implementation (if not needed).
I will check give it a try as soon as possible and be back here to report my findings. Thanks!

**Comment by samsp-msft** [comment]
should we do a sample for this?

**Comment by KlemensGenetec** [comment]
For me that would also be an important feature since that opens up a lot of possibilities. Since I was asked in #1455 to copy my notes here is how i solved it  for the time being.

For now i am doing LoadFromConfig to get the routes, letting this parse and then doing this:

```
var oldConfig = services.BuildServiceProvider().GetRequiredService<IProxyConfigProvider>();

builder.Services.AddSingleton<IProxyConfigProvider>(new InMemoryConfigProvider(oldConfig.GetConfig().Routes));
```

This approach is bad because then I need to build the ServiceProvider in the ConfigureServices method.
However, looking at ConfigurationConfigProvider there is a lot of logic for the parsing from a config file so i don't want to recreate/copy that.

I have a few suggestions how it could be done better

1. The entire ConfigurationConfigProvider could become public
2. If that exposes too much logic, extracting the parsing logic into a new interface so that this can be used in other IProxyConfigProvider implementations would also work.
3. Maybe it should be allowed to use multiple IProxyConfigProviders and having their configurations combined when the proxy is used.
4. Another option would be to separate the routes from the cluster configuration so that different providers can contribute these. But that seems very limited in general utility.

To me 1 or 2 would be enough because then you can manually combine the providers together. It would require ever consumer that needs this functionality to recreate the merging/conflict handling logic but it is probably acceptable for now.

In addition, I believe the InMemoryConfigProvider should also go into the library since its also a very common scenario. Now it is in the samples and will be copied in a lot of projects.

Otherwise, I didn't encounter any issues with the library, its great for a first version!

**Comment by Tratcher** [comment]
Option 3 seems likely/useful, if we can decide on how to combine the data sets and resolve conflicts. The infrastructure is almost ready for this now, and we wouldn't have to expose new surface area.

**Comment by karelz** [comment]
Triage:
- Scoping to merging routes and clusters nodes is reasonable. If there is overlap, based on policy we should act (one wins vs. error).

**Comment by pinkfloydx33** [comment]
This would definitely be appreciated. Glad there's a PR for it.

I actually implemented this morning a solution that removes the config-config provider from DI and then uses the factory from the descriptor to inject it into my own class. That class returns the original config plus a dynamically generated set of routes based on a list (that follows the same "template") allowing us to keep the config.json short without relying on a massive regex route constraint.

This would definitely ease that a bit as we'd no longer need to track/wrap the initial config, nor hack the DI.. and can just add on the bits what we need seperately
